### ISSUE TITLE
Delete documents in SharedSpace

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#111]
### Story: 

#48

### Design: 

https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=2239%3A2178

### Description:
- API:
```

```

- `SharedSpaceDocumentRepository`
```
Future<WorkGroupNode> removeSharedSpaceNode(
    SharedSpaceId sharedSpaceId,
    WorkGroupNodeId sharedSpaceNodeId);
```

### DoD:
- Can delete single document
- Can delete multiple documents

**Comment by datnguyenhuy** [comment]
Function works well !
Tested in Redmi 6 Pro
Version 0.8.0
