### ISSUE TITLE
Download stops after device is locked automatically

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#116]
**Description**
Downloading should run/resume after device is locked automatically

**Reproduction Steps**

Set up auto-lock time for device
Start exporting a file
Wait until device is locked automatically
Un-lock the screen
Check download process

**Expected result**
Download continues

**Current behavior**
Download dialog shows in a few seconds then closes

**Context**
Iphone 11 Pro Max

**Additional information**
frequency, log files,...

**Comment by hoangdat** [comment]
@dieptran88 please compare this ticket to other application (GDrive, OneDrive, ...)

**Comment by dieptran88** [comment]
With other app, The downloading is continued when the device is lock. When user unlocked account, if the downloading is completed, there will be a toast message in some seconds

**Comment by hoangdat** [comment]
@manhduc-nguyen please verify it also

**Comment by manhduc-nguyen** [comment]
https://images.zenhubusercontent.com/309616769/90910497-8206-47aa-b947-ffb5361750c6/no_bug.mp4

Tested on iPhone XR 14.0.1 and iPhone 11 Pro 14.4 and I could not reproduce it.
