### ISSUE TITLE
Unable to export image to Linshare

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#118]
**Reproduction Steps**

In MySpace, export an image file
Choose destination as Linshare

**Expected result**
2 solutions:

If Linshare app is available, image file should be exported successfully to Linshare (duplicate the file)
OR if it is not supported, please hide Linshare option

**Current behaviour**
Linshare option is available as destination but when user selects that option, nothing happens
https://images.zenhubusercontent.com/309616769/68d07cfe-de2d-4862-9fba-bd89bd72a885/rpreplay_final1608198165.mp4

**Context**
Iphone 11 Promax

**Additional information**
frequency, log files,...

**Comment by hantt12** [comment]
This is what happens now. Tested in Iphone 11, ios 14.4. Linshare 0.3.0 (34)
https://images.zenhubusercontent.com/309616769/4cbb8113-7212-4eec-b2cd-58ad8f56c53c/img_4170.mp4

**Comment by hoangdat** [comment]
Please compare to other app (google drive, dropbox,...)
