### ISSUE TITLE
Keyboard does not hide when tap outside, tap login, tap back

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#119]
**To Reproduce:**

Open Linshare App
Fill out some information like server, username, password
Tap outside/ tap login/ tap back
Verify issue

**Actual Results:** Keyboard does not hide when tap outside, tap login, tap back
https://images.zenhubusercontent.com/309616769/8d002608-fc47-46e4-884a-36b5b076a03a/l.mp4

**Expected Results:** The keyboard should hide when tap outside, tap login, tap back
**Context**
Tested on Iphone 11 Promax

**Comment by TuanQA92** [comment]
After I completed entering info like  like server, username, password. Then I tap on outsite, but the keyboard still displays.  
Expected: The keyboard will be hidden when I tap outsite.
Please see the video attached below: 
https://images.zenhubusercontent.com/309616769/55319871-91d7-43b5-9ac0-023a5310bc81/skype_video1.mp4

**Comment by datnguyenhuy** [comment]
After I completed entering info like like URL, username, password. Then I tap on outsite, The keyboard is no longer displayed 
https://images.zenhubusercontent.com/309616769/443ca900-87c4-42bf-974c-9ec189f67a85/signal_2021_05_25_114915.mp4
