### ISSUE TITLE
List of files is not auto updated after user deletes one file

### ISSUE THREAD

**Issue by hantt12** [linagora/linshare-mobile-flutter-app#127]
### Description
After user successfully deletes a file, list of files should be refreshed and updated automatically

#### Reproduction Steps

1. Connect network and delete a file from MySpace
2. Check the list of files in MySpace

### Expected result
Deleted file is no longer in the list

### Current behavior

Delete file is still there. User has to refresh the list to see it disappear
https://images.zenhubusercontent.com/309616769/9b3c35aa-45b1-4342-9b0c-cb2b62dd737a/img_0571.mp4
### Context

Iphone 11 Promax 
Linshare app 0.1.0 (33)

### Additional information

frequency, log files,...

**Comment by hoangdat** [comment]
@manhduc-nguyen Please find the generic way to update the list after executing operator

**Comment by manhduc-nguyen** [comment]
the problem is after we successfully removed a document, we will dispatch MySpaceAction. then we will dispatch StartMySpaceLoadingAction to start reload the list. StoreConnector only receiving LoadingState and skip RemoveDocumentViewState because it happens too fast.
