### ISSUE TITLE
[Story] As an user, i want to delete multiple files in Myspace 

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#139]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

*https://app.zenhub.com/workspaces/linshare-flutter-5fe04e3547c3510015c66915/issues/linagora/linshare-mobile-flutter-app/43

## Definition

  Given that i am a Linshare user
*  After log-in successfully, i go to Myspace
*  On Myspace, i can see list of files 
*  When I long-press on a file from the list, the file is selected and the multiple files option bar will be displayed.
*  Now in each file, there will be a checkbox. If i tick that box, the file is selected and the selected file count field at the top bar is added. 
*  In the multiple files option bar, i can see some icons: 
   *  Share icon
   *  Download icon
   *  Delete icon
   *  Checkbox: If i tick the box, all the file in Myspace will be selected. If i un-check the box, all the files will be deselect. 
*  After selecting multiple files, there are 2 ways to delete selected files: 
   *  I click on icon Delete on the bottom bar
   *  Or i can click on three-dot button on top bar, a bottom sheet will be opened. I choose the option " Delete"
*  The will be a confirmation popup. If i choose Yes, all the selected files will be deleted. 
*  After deleting, i cannot see those files in Myspace.

[Back to Summary](#summary)

## Screenshots

None

## Misc

None

[Back to Summary](#summary)

**Comment by qpnguyen199** [comment]
Hi, here is the IU design for this story
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=1714%3A1433
