### ISSUE TITLE
Account's information details 

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#142]
### Story: 

#141

### Description:
- whenever `getCredentials` success, `getAuthorizedUser`
```
class UserRepository {
    Future<User> getAuthorezedUser();
}

....

@GET("/authentication/authorized")
@Headers("Accept: application/json")
fun getAuthorizedUser(): User
```
- then store it to state
- create an item in side menu to account details
- screen to show account details

### DoD:
- user is stored in State
- all information of user is showed

**Comment by hantt12** [comment]
Please add available quota as expected

Currently in 0.5.0 (39)

![IMG_0133.PNG](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/527a47c4-04e5-44da-8419-9bb97bb38172)
