### ISSUE TITLE
[Story] As an user, i want to copy a file from Received shares to Myspace 

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#159]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

https://app.zenhub.com/workspaces/linshare-flutter-5fe04e3547c3510015c66915/issues/linagora/linshare-mobile-flutter-app/130

## Definition

- Given that i am a Linshare user

- Given that function Received shares is enabled in Admin  

- After log-in, i go to Receive shares list 

- I click on three-dot button and choose Copy to Myspace

-  I can see the successful notification:" The file has been copied into your Personal Space"  and a button View

- When i click button View, the system will open Myspace list and the copied file is selected  

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by qpnguyen199** [comment]
Hi, here is the UI design for this story
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=82%3A901
