### ISSUE TITLE
[Story] As an user, i want to copy a file from  a workgroup to Myspace 

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#161]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

https://app.zenhub.com/workspaces/linshare-flutter-5fe04e3547c3510015c66915/issues/linagora/linshare-mobile-flutter-app/160
## Definition

- Given that i am a Linshare app user

- Given that function Workgroup is enabled in Admin 

- After log-in successfully, i go to Shared space, i can see the list of workgroups

- When click on a workgroup, i can see the list of files in that workgroup

- I click on three-dot button of a file and choose Copy to Myspace 

-  System will display successful message

- When I open My space screen, I can see the copied file in the list 

- An user can copy file from Workspace to Myspace dispite of his role to the workgroup. 

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by qpnguyen199** [comment]
Hi, here is the UI design for this story
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=2550%3A1
