### ISSUE TITLE
[Story] As an user, i want to Search document in Myspace

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#166]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC
#165
#### UC1. Quick search by file name 

- Given that i am an Linshare app user

- After log-in successfully, i go to Myspace screen and see the list of file 

- I click on Icon Search, the search bar will be displayed on the top of screen and the keyboard is popped up 

- I input some text on search bar and touch Search icon on keyboard, system will show instantly the list of files that have name containing inputted text. 

- Otherwise, not found screen need to be shown

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@qpnguyen199 please add desgin link for this

**Comment by qpnguyen199** [comment]
Here is the UI Design link:
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=31%3A4

**Comment by hoangdat** [comment]
@manhduc-nguyen it is for you
