### ISSUE TITLE
[Story] As an user, i want to search workgroup in shared space 

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#167]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC
#165

#### UC1. Quick search by name 

- I Logged in the system successfully 

- From menu, go to Workspace

- When click on Search icon, I can see the search bar on top of the screen 

- I input some text on search bar and touch Search icon on keyboard, system will show instantly the workgroups that have name containing inputed text. 

- Otherwise, not found screen need to be shown

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@qpnguyen199

**Comment by qpnguyen199** [comment]
Hi, here is the UI Design for this story:
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=224%3A0
