### ISSUE TITLE
[Story] As an user, i want to search  files/folders of a workgroup 

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#168]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

#165

## Definition

- Given that i am a Linshare app user 

- After log-in successfully, i go to Shared Space and see the list of workgroups 

- I click on a Workgroup, i can see the list of files/folders of that workgroup

- I click on Search icon, the search bar is displayed with the keyboard popped up. 

 - I input some text on search bar and touch Search icon on keyboard, system will show instantly the files/folder of selected workgroup  that have name containing inputed text. 

- Otherwise, not found screen need to be shown.

- When i go to child folder of that workgroup, i can continue searching files/folders of that child folder 

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@qpnguyen199 please provide design link for this

**Comment by qpnguyen199** [comment]
Hi, here is the UI design for this story:
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=2576%3A0
