### ISSUE TITLE
[Story] As an user, i want to Delete my workgroup 

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#169]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

#165

## Definition

- Given that i am a Linshare app user 

-  I logged in the system successfully

- From menu, I go to Workspace

-  I touch three dots button of a workgroup

- Choose option Delete from the Droupdown list 

- A confirmation popup is displayed, I confirm to delete workgroup

- After deleting workgroup from the list in Workspace screen,the system shows a successfully delete notification. 

- Only admin of workgroup can delete that workgroup. If the user is not admin of the workgroup, the option Delete workgroup will be hiden from the bar 

[Back to Summary](#summary)

## Screenshots

UI/UI
https://www.figma.com/file/NGap1XrsfXvsublLTjHEMn/LinShare-Android-App---Phuong?node-id=721%3A4395
[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by qpnguyen199** [comment]
Hi, here is the UI design for this story:
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=2803%3A1
