### ISSUE TITLE
Search in MySpace

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#183]
### Story: 
#166

### Description:
- Create `SearchInteractor` 
```
List<Document> search(List<Document> allDocuments, QueryString query)
```

### DoD:
- search only available when app in online mode
- search should be show empty with no result
- search query will be debounce in execute.

**Comment by hantt12** [comment]
Search result is not quite correct as you can see this the image below. The first file name does not include "e" (including the file extension)

![IMG_0135.PNG](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/05ae50a7-460d-43c0-8fde-769d2e29777c)
