### ISSUE TITLE
Export files in Workgroup (iOS)

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#185]
### Story:
#47

### Description:
- API:
```
"shared_spaces/{sharedSpaceId}/nodes"
```
- SharedSpaceDocumentRepository
```
Future<Uri> downloadDocumentIOS(...)
```
(reference to `downloadDocumentIOS` in DocumentDataSource)
### DoD:
- `Export` is not showed  when selected document include folder
- `Export` is not showed on Android platform
- Files are exported to device after downloading

**Comment by hantt12** [comment]
App crashes while exporting png/jpg

https://github.com/linagora/linshare-mobile-flutter-app/issues/314
