### ISSUE TITLE
Download files in Workgroup (Android)

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#186]
### Story:
#47

### Desc:
- API:
```
"shared_spaces/{sharedSpaceId}/nodes"
```
- SharedSpaceDocumentRepository
```
Future<List<DownloadTaskId>> downloadDocuments(List<> ids, Token token, Uri baseUrl)
```
(refer to DocumentDataSource)

### DoD:
- `Download` is not showed  when selected document include folder
- `Download` is not showed on iOS platform
- Files are download to device after downloading

**Comment by datnguyenhuy** [comment]
Function works well !
Tested in Redmi 6 Pro
Version 0.8.0
https://images.zenhubusercontent.com/309616769/d50140cf-9d16-4204-b502-dc48d0f110dc/signal_2021_05_25_113710.mp4
