### ISSUE TITLE
Unable to download file

### ISSUE THREAD

**Issue by hantt12** [linagora/linshare-mobile-flutter-app#189]
### Description
Unable to download file from MySpace

### Expected result
App asks user where to save the file and the file can be downloaded successfully

### Current behavior
Keep showing Preparing to export screen for a long time even though it's just a small file

#### Reproduction Steps
1. Go to MySpace on iPhone
2. Try to export a file
https://images.zenhubusercontent.com/309616769/37dc35f9-228c-4bdb-b352-9fcb5242053f/rpreplay_final1613617208.mp4

### Context

Iphone 11, iOS 14.4
Linshare flutter 0.3.0 (34)

**Comment by hantt12** [comment]
Update: file can be download but it takes a long time even though the file size is small
Let's observe more to see if it's the problem of app or server

**Comment by manhduc-nguyen** [comment]
tested again. more stable to download now

**Comment by ghulamostafa** [comment]
You can check on this article for how to download and then view it later:
https://ghulamustafa.com/2021/03/19/how-to-download-files-and-in-flutter-and-read/
