### ISSUE TITLE
Disable SharedSpace in app when admin disable Workgroup

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#191]
### Story:
#163: UC1 - UC4

### Desc:
- API:
```
    @GET("functionalities")
    @Headers("Accept: application/json")
    suspend fun getAllFunctionalities(): List<Functionality>
```
- Functionality Repository
- List of functionalities should be store in AppState

### DoD:
- Will check the functionalities whenever app start up
- Shared Space is not visible in side menu for this case
- `Copy to Shared Space` action is not visible  also
- Can not select destination when upload from outside app

**Comment by hantt12** [comment]
Currently the menu is only updated if user kill/restart the app or restart device
If not, the menu item is still there even though it is disabled from admin site

**Comment by hantt12** [comment]
Menu is disabled only when user kills app or starts device. This is still an issue because many people does not have the habit of killing apps
