### ISSUE TITLE
Delete workgroups

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#192]
### Story:
#169

### Desc:
- API:
```
@DELETE("/shared_spaces/{sharedSpaceId}")
```
- SharedSpaceRepository

### DoD:
- `Delete` action only visible with user have the permission
- Can delete the workgroup
- Toast message is showed
- List of workgroup is refresh after delete
- Delete multiple workgroup

**Comment by datnguyenhuy** [comment]
Function works well !
Tested in Redmi 6 Pro
Version 0.8.0
