### ISSUE TITLE
[Story] As an user, i want to search document in Received shares

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#194]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

#165

#### UC1. Quick search by file name 

- Given that i am an Linshare app user

- After log-in successfully, i go to Received shares screen and see the list of file 

- I click on Icon Search, the search bar will be displayed on the top of screen and the keyboard is popped up 

- I input some text on search bar and touch Search icon on keyboard, system will show instantly the list of files that have name containing inputted text. 

- Otherwise, not found screen need to be shown

- In result screen, after i executing an action on a file (copy, move, delete, duplicate...), the result screen will be kept with the search box until i click on button Close

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@qpnguyen199 please add design link

**Comment by qpnguyen199** [comment]
Hi, here is the UI design for this story:
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=2808%3A1
