### ISSUE TITLE
[Story] Export file in Received Shares 

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#199]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

#130

## Definition

*  Given that i am an Linshare app user 
*  After log-in to Linshare, i am directed to Myspace and see the list of files 
*  I click on 3-dots button of a file, i can see option "Open in"

**UC1** Download to My iphone

*  When i click button Open in, the selected file is started to be downloaded, i can see a popup showing Downloading progress
*  After app downloaded file successfully, the [Pick destination] screen will be shown 
*  On this screen, I can see the destination list. I can enable/disable this destination list
*  Given that I enabled the option Save to files
*  When i choose Save to Files, a destination screen will be opened that allow me to choose one folder On my iphone
*  After choosing a folder and click button Save, the file will be saved to the destination folder and the Pick destination screen will be closed. 
*  Now when i open My files on my phone, and go to the destination folder, i can see the downloaded file here. 

**UC2** Cancel download 
*  Given that when i click button Open-in, the selected file is started to be downloaded and i see the Downloading progress popup
*  On the popup  i click button Cancel, the downloading is stopped and the popup is closed.

**UC3** Download to a new created folder on my device 

*  when i click button Open in, the selected file is started to be downloaded, i can see a popup showing Downloading progress
*  After app downloaded file successfully, the Pick destination screen will be shown
*  On this screen, I can see the destination list. I can enable/disable this destination list
*  Given that I enabled the option Save to files
*  When i choose Save to Files, a screen will be opened that allow me to choose one folder On my iphone
*  On the top right of the screen, i can see a button Create new folder
*  When i click on this button, I can see Create new folder popup
*  I can input the folder name and click button to Done, the new folder in created under On my iphone 
*  This new created folder will become the child folder of the folder selected right before. 
*  Now the new created folder is selected as the destination folder, if i click button Save, the file is saved to this new folder. 

**UC4** Close app when downloading 
*  Given that i  i click button Open in, the selected file is started to be downloaded, i can see a popup showing Downloading progress
*  Now i close app while the downloading is still in process 
*  The downloading process is still continuing in background
*  After a while, i open the app again, i can continue the process as normal, without interruption.

**UC5** Netwotk error while downloading 

*  Given that i am downloading process 
*  If the network is disconnected, the system will display an error message and the downloading process will be stopped. 

[Back to Summary](#summary)

#### Download progress bar

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/3543e21b-0d7e-453a-a614-e908d13286a4)

#### Pick destination Screen 
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/bbe9f00c-69cc-4e9e-9bf5-4404c23120ec)

#### Save to Files 
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/f0e914d6-10c4-4775-bfb1-86cdfb0ecfce)

#### Create new folder 
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/44373b80-5067-4812-946e-55b15807f02b)

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@qpnguyen199 please add design link

**Comment by qpnguyen199** [comment]
Hi, here is the UI design for this story:
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=2809%3A422
