### ISSUE TITLE
[Strory] As an user, i want to export (download) multiple files in Received shared 

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#204]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

#43

## Definition

* Given that i am a Linshare user
* After log-in successfully, i go to Received shares and see the list of files that i have been shared with 
* When I long-press on a file from the list, the file is selected and the "multiple files option bar" will be displayed.
* Now in each file, there will be a checkbox. If i tick that box, the file is selected and the selected items counting field at the top bar is added.
* In the multiple files option bar, i can see some icons:
  * Download icon
  * Delete icon
  * Checkbox: If i tick the box, all the file in the workgroup will be selected. If i un-check the box, all the files will be deselect.
* After selecting multiple files, there are 2 ways to download multiple selected files :
  * I click on icon Download on the top bar
  * Or i can click on three-dot button on top bar, a "list of actions" popup will be open. I can see the full options: Download, Delete, Copy to a workgroup, Copy to Myspace. I touch the button Download 
*  The downloading is executed  to save the selected files:
      * If device is Android, the notifcation bar will display all the downloaded file with its's status
      * If the device is IOS, there will be a destination picker screen that allow me to choose the destination

*  When the download is completed, I can see the notification on the device. When I touch the noti, I can see local folder containing downloaded files. 
*  If there is an error that make downloading fails (connection, file size, storage space...), i can see an error notification on the device. 

[Back to Summary](#summary)

#### Received shared
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/5ebc2174-3c32-4af6-8f29-b010ab76c8cf)

#### Actions bar 
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/f49caa2a-7c24-4131-82f0-34b89882c6e1)

#### List of actions popup
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/fba6296d-e62d-49b7-8406-30d34651df72)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@qpnguyen199 Please add design link for story

**Comment by qpnguyen199** [comment]
Hi, here is the UI design for this story:
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=2832%3A1
