### ISSUE TITLE
[Story] As an user, i want to view detail information and list of member/role of workgroup 

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#205]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

#160

## Definition

**1. View workgroup information**
 

- I Logged in the system successfully 
-  From menu, go to Shared Space and see the list of workgroups that i have one of any roles: Admin, contributor, writer, reader
- I touch three dots button of a workgroup
- Choose “Details” from Dropdown list 
- I click on tab Details
- I can see 3 tabs: First tab I can see basic information of a workgroup:

         - Name
        - Used space
        - Create time
        - My rights
        - Max file size 
        - Modification time
        - Description
    • When i already open a workgroup, i can also click icon "i" at the header to view workgroup's detail information. (Check design)

**2. View workgroup member and role**

- I Logged in the system successfully 
- From menu, go to Shared space and the the list of workgroups that i have one of any roles: Admin, contributor, writer, reader
-  I touch three dots button of a workgroup
-  Choose “Details” from Dropdown list 
- I can see 3 tabs: Click to the Member tab, i can see  the member list of this workgroup and each member’s role, including me.
-  When I click button back on the top, the system goes back to the previous screen.

**3. Add/Edit workgroup description**
- Given that I am an user in detail tab of a workgroup in Shared space 
- I can see the field Description. When I click on the button Edit, I can add (if there is no description) or edit (if there is already a description). 
- I can only add/edit if i am the contributor/writer/admin of the workgroup. If i am the reader, i can only view description if any. 
-  I click button cross or enter, the Description is saved. 
- When I close workgroup detail screen and comeback, I can see the description updated

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@qpnguyen199 Please add design for this story

**Comment by qpnguyen199** [comment]
Hi, here is the UI design for this story:
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=279%3A252
