### ISSUE TITLE
[Story] As an user, i want to edit member's role in my workgroup

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#210]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

#160

## Definition

- Given that i am a Linshare user 
-  I Logged in the system successfully 
- From menu, go to Shared Space and see the list of workgroup 
- I touch three dots button and Choose “Details” from Dropdown list, a new screen is opened with 3 tabs: Detail, Members, Activities
-  I choose the tab Members and see the list of existing members with their role. 
    - If am admin the Workgroup,  On the Existing member list, when I touch the symbol Edit at the row of member I want to edit, the dropdown list will be dispayed – included 4 roptions: Reader, Admin, Contributor, Writer. The current role will be marked. I only can choose one of the 3 others.
    • I touch to choose one new role for that member and it is applied immediately 
    • Only admin of a Workgroup can edit member's role. Users with other roles will not see the Edit member symbol. 

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@qpnguyen199 Please provide design

**Comment by qpnguyen199** [comment]
HI, here is the UI Design for this user story:
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=2841%3A1

**Comment by hoangdat** [comment]
Implemented in #331
