### ISSUE TITLE
[Story] As an user, i want to view activities of my workgroup

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#212]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

#160

## Definition

- Given that i am a Linshare app user 
-  I logged in the app successfully
- From menu, I go to Shared Space and see the list of my workgroups 
- I touch three dots button of a workgroup and choose Details from the Dropdown list , a new screen will be displayed with 3 tabs: Details, Members, Activities, i choose the tab Activities. 
-  The Activities screen shows history of workgroup. When there is an action to the workgroup, it will be recorded and added to Workgroup activites screen: 
        ◦ Create work group
        ◦ Add member to workgroup
        ◦ Rename workgroup
        ◦ Create folder in workgroup
        ◦ Upload file/folder in workgroup
        ◦ Action to a file in the workgroup: Rename, Duplicate, Copy, Move, Delete
        ◦ Action to a folder in the workgroup: Rename, Move, Delete 
        ◦ Copy a file from Myspace/ Recieved shares to the workgroup
 
- Each activity includes: Objective, Description, Time,  Person who executed the action. 
-  The system will define if the action is implemented by me or not and displayed "By me " in the action description 

> For example:   
> 
> 20210125_144830.mp4
> Copy : You have created the document : 20210125_144830.mp4 into another wokgroup, from your Personal Space.
> 3.4 GB | 12 minutes ago | by Me
> 

- User with any role to the workgroup can view screen Workgroup activities. 

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@qpnguyen199 Please provide design link for it

**Comment by qpnguyen199** [comment]
Hi, here is the UI Design for this story:
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=2864%3A1

**Comment by hantt12** [comment]
Please check some bugs: 
https://github.com/linagora/linshare-mobile-flutter-app/issues/434
https://github.com/linagora/linshare-mobile-flutter-app/issues/435
https://github.com/linagora/linshare-mobile-flutter-app/issues/436
