### ISSUE TITLE
[Story] As an user, i want to Share a file with device's contacts 

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#217]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Definition
    

- Given that I am an Linshare app user
- I log in Linshare app successfully and from the menu I go to Myspace
- I click on three-dots button of  a file and choose option Share 
- When Share screen is opened the first time, I can see a popup asking that if I allow Linshare app to access device contact. When I upload file outside app, this popup is also displayed for the first time the screen Upload is opened. 
- If I choose No, the popup close and I can continue input recipients as usually.
- If I choose Yes, the popup close and when I start to input the field Recipient, system will search the keyword and suggest recipients from 2 sources :
        ◦ From the Linshare system through API
        ◦ From the device contact: the suggested recipients are contacts that have name/email containing inputted keyword. 
  -  If a contact contains more than 1 email, all the emails are shown with a Name, and I can choose an email to share document.      

 **Note: The permission to the device contact is saved for the next times.** 

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@qpnguyen199 Please add design link

**Comment by qpnguyen199** [comment]
Hi, here is the UI Design for this story:
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=2893%3A9945
