### ISSUE TITLE
Download documents in Received Share

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#222]
ANDROID

### DoD:
- Download file and multiple files

**Comment by hantt12** [comment]
This feature does not work as I checked today 8 April 2021
Version 0.5.0 (39)
tested in Iphone 11 and iPhone XR

**Comment by datnguyenhuy** [comment]
Function "Download" works well !
Tested in Redmi 6 Pro.
Version 0.8.0
https://images.zenhubusercontent.com/309616769/2afffcd5-d07c-4ef7-a2f7-42f92434a24b/signal_2021_05_25_112145.mp4
