### ISSUE TITLE
Share a file with device's contacts

### ISSUE THREAD

**Issue by manhduc-nguyen** [linagora/linshare-mobile-flutter-app#228]
**DoD**

- Request contact permission the first time go to Share screen.

- Can suggest matched emails from device's contact

- Can share to emails which are not from linshare's domain

**Description**
- install a forked version of this library [contacts_service](https://github.com/linagora/flutter_contacts) to modify and get contacts 

- Add a function to search contacts by contact's name or contact's email to `contacts_service ` library (for both Android and iOS)

- using [permission_handler](https://pub.dev/packages/permission_handler) (already implemented to our project) to check and request contact permission. Need adding PermissionGroup.contacts to `Podfile` for `permission_handler` library working properly

**Repository**

`Future<List<AutoCompleteResult>> getAllContactsByNameOrEmail(SearchQuery searchQuery)`

**Comment by datnguyenhuy** [comment]
MySpace => press the 3-dot button on the file you want to share => Select "Share" => Enter recipient's email => Suggestion box appears => Crash
https://images.zenhubusercontent.com/309616769/02a70ebe-b3e0-4b44-bffe-036b063e9d73/signal_2021_05_21_143955.mp4

**Comment by huynguyennovem** [comment]
Tested on:
- Version 1.0.0 (features_v2 branch)
- Android 11
- iOS 14.5

https://images.zenhubusercontent.com/309616769/c69e773d-7fcf-4ab6-8bfa-bf9c3dc8281d/demo_fix_bug_share_file_to_contact.mp4

**Comment by huynguyennovem** [comment]
This bug (logged by `datnguyenhuy`) does not happen again on:
- Version 1.0.0 (features_v2 branch)
- Android 11
- iOS 14.5

https://images.zenhubusercontent.com/309616769/c69e773d-7fcf-4ab6-8bfa-bf9c3dc8281d/demo_fix_bug_share_file_to_contact.mp4

**Comment by hoangdat** [comment]
@huynguyennovem please check the issue more careful, this issue has with device contact

**Comment by huynguyennovem** [comment]
No crash without granting permisson too:

https://images.zenhubusercontent.com/309616769/f6bb5093-5acf-4bad-80f1-ff04249064cb/demo_fix_bug_share_file_to_contact_2.mp4

**Comment by hoangdat** [comment]
As I understand, no issue with it, why you not close? @huynguyennovem

**Comment by huynguyennovem** [comment]
Ok, can close this
