### ISSUE TITLE
Copy WorkGroupNode to SharedSpace

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#234]
### Desc
- SharedSpaceDocumentRepository
```
fun copySharedSpaceNode() {}
```
- API
```
@POST("/shared_spaces/{destinationSharedSpaceId}/nodes/{destinationParentNodeId}/copy")
@Path("destinationSharedSpaceId") destinationSharedSpaceId: String,
@Path("destinationParentNodeId") destinationParentNodeId: String? = null,
@Body CopyRequest
```

### DoD
- select right destination which user have permission (Destination picker)
- documentNode is copied from a SharedSpace to another SharedSpace
-

**Comment by datnguyenhuy** [comment]
Function works well !
https://images.zenhubusercontent.com/309616769/c12c893a-0a3f-4fde-ae5a-62da0809f921/signal_2021_05_21_142402.mp4
