### ISSUE TITLE
Update to support Android 30

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#237]
### Description:
- Android app from flutter is not deployed to Play store because the `targetSdkVersion` is 28 (lower than current Android app in store)

### DoD:
- App can download files to public folder with Android 30
- Can deploy to Play store

**Comment by huynguyennovem** [comment]
- Update on 24 Mar 2020: [https://docs.google.com/presentation/d/1ZsVnngzw78APFQYL3PFNSNxsyNruQZIcRn2MclH1B9k](https://docs.google.com/presentation/d/1ZsVnngzw78APFQYL3PFNSNxsyNruQZIcRn2MclH1B9k) 
Summary:
   - Use Storage Access Framework ([SAF](https://developer.android.com/guide/topics/providers/document-provider)) when saving to downloaded file into public storage
      - Result: Can save the downloaded file into public storage
      - Limitation: Can not pick destination is Download directory

(To be continue...)
