### ISSUE TITLE
[Dev] Sort files in SharedSpace

### ISSUE THREAD

**Issue by manhduc-nguyen** [linagora/linshare-mobile-flutter-app#241]
**DoD**

- SharedSpace list will be sorted by `Modification Date descending` by default.

- Show sort status row below action bar

- When tap on sort status row, show bottom sheet of other sort options, user can select different options.

**Desciption**

- See [Sort files in MySpace](https://app.zenhub.com/workspaces/linshare-flutter-5fe04e3547c3510015c66915/issues/linagora/linshare-mobile-flutter-app/240) for similar solution

**Comment by hantt12** [comment]
Bug https://github.com/linagora/linshare-mobile-flutter-app/issues/304

**Comment by datnguyenhuy** [comment]
Function works well !
