### ISSUE TITLE
[Story] As an user, i wan to copy file from one workgroup to another workgroup 

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#246]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC
#160

## Definition

UC1. As an user, i want to copy a single  file from one workgroup to another workgroup

- Given that i am an Linshare user

- After log-in successfully, i go to Shared Space and choose one workgroup

- I can see the list of files/folders inside that workgroup. 

- I click on three-dots button of a file and choose Copy to Workspace

- The pick destination screen is displayed. I can see all the workgroups that i have Admin/writer/contributor role.

- I pick one workgroup in the list and click button Copy here 

- If the copying is successfully, there will be a toast message. 

- If the copying is not successfully, there will be an error message

UC2. Copy file to a new created workgroup/folder 

- Given that i am copying file 

- In pick destination screen, i can see the list of workgroups that i have role admin/writer/contributor 

- I can also choose a workgroup then see the list of folders of that workgroup and choose a folder as destination 

- In Pick destination screen  can click button "+"  to create a workgroup or a folder, depending on the current position. 

- A textbox will be displayed that i can input new created workgroup/folder' name. 

- After the new workgroup/folder is created, i can choose it as the destination and continue copying process

UC3. Copying mutiple files from a workgroup to another workgroup 

- Given that i am a Linshare user

- After log-in successfully, i  go to Shared Space and click on a workgroup 

- I can see the list of files/folders inside that workgroup

- When I long-press on a file from the list, the file is selected and the multiple files option bar will be displayed.

- Now in each file/folder, there will be a checkbox. If i tick that box, the file/folder is selected and the selected items counting field at the top bar is added. Only when all items i selected are files, the option Copy is enabled on the action list below.

- In the multiple files option bar, i can see some icons:

         Download icon
         Delete icon
         Move icon
         Checkbox: If i tick the box, all the files/folder in the workgroup will be selected. If i un-check the box, all the files/folders will be deselect.

- After selecting multiple files, i can click on three-dot button on top bar, a list of actions will be open. I choose the option " Copy to Shared Space", the pick destination screen will be opened 

- After choose a workgroup, i can see the list of files/folder inside that workgroup. I can select that workgroup or a folder inside as the destination.

- I click button Copy here , the system copied files to the selected destionation workgroup/folder and displays successful toast message.

- When I open the destination workgroup/folder, I can see copied file displayed.

_Additional rules:_

- In Pick destination screen: In workgroup list screen, i can only see the workgroup that i have role admin/contributor/writer. i cannot see the workgroup that i only have reader role

- In the file/folder list screen, all the files are disabled so that i cannot choose.

 

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@qpnguyen199 Please addd design link for this story

**Comment by qpnguyen199** [comment]
Hi, here is the UI Design for this story:
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=2994%3A1134
