### ISSUE TITLE
List members with their role

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#247]
### Story
#205 - `UC2`

### Desc
- SharedSpaceMemberRepository
```
fun getMember() {}
```
- API
```
``` 

### DoD
- Member tab in details screen of Workgroup
- All members with their role is listed

**Comment by hantt12** [comment]
Failed to show members and their roles

![IMG_4952.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/b05af8d5-28a2-4939-b5cb-453ae3c88e80)
