### ISSUE TITLE
Add members to WorkGroup

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#248]
### Story
- TBD

### Desc
- `SharedSpaceMemberRepository`

### DoD
- Member will be added successfully to Workgroup
- Role must be selected before add member

**Comment by datnguyenhuy** [comment]
Function "Add Member" works well !
https://images.zenhubusercontent.com/309616769/28dd5e43-382e-4d12-949f-ef857037ceae/signal_2021_05_20_120647.mp4
