### ISSUE TITLE
Adjust the distance between elements in Upload file screen

### ISSUE THREAD

**Issue by hantt12** [linagora/linshare-mobile-flutter-app#252]
Distance between elements are not balanced

- Header and file name
- File name and "Add recipients" text
- "Add recipients" and "Add people" field

![IMG_0095.PNG](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/bece5add-522b-45f7-9040-238a6a3edb8f)

**Comment by datnguyenhuy** [comment]
![image.png](https://images.zenhubusercontent.com/606bcc9093306911d9ef4d58/74eeb99e-68b7-49e5-b208-3cf6dce081b1)
