### ISSUE TITLE
search term should be cleared after user Copy to Workgroup from search result

### ISSUE THREAD

**Issue by hantt12** [linagora/linshare-mobile-flutter-app#255]
#### Reproduction Steps
1. User logs in and open MySpace
2. User clicks on Search icon
3. User inputs a search term to search box 
4. In the search result list, view list of actions for a file
5. Select "Copy to a workgroup"
6. Search a workgroup and click Copy Here

### Expected result
Show all files in MySpace

### Current behavior
Show list of files as search result (but without search box)

### Context

Iphone XR
Linshare 0.4.0 (36)

**Comment by hoangdat** [comment]
@dieptran88 please verify this issue?

**Comment by dieptran88** [comment]
I confirmed the current behavior,
Expected result: Show the previous screen which is search result screen with search box

**Comment by hoangdat** [comment]
v2.0.0-alpha02
