### ISSUE TITLE
User is no longer able to upload if he kills app and disconnect/connect to network

### ISSUE THREAD

**Issue by hantt12** [linagora/linshare-mobile-flutter-app#257]
### Description
if user kills app and disconnect to network, he is not able to upload when he connect to network again

#### Reproduction Steps
1. User disconnect from network
2. User kill Linshare app
3. User open Linshare app again
4. User connect device to network
5. User uploads file

### Expected result
user is able to upload file

### Current behavior
User is not able to upload file

### Context

Iphone XR
Linshare app 0.4.0 (37)

**Comment by hoangdat** [comment]
Root cause: `User` is not refresh when reconnect in app. So `quotaId` is null, can not verify quota to upload
