### ISSUE TITLE
Workgroup/Files should be deselected after being copied to MySpace

### ISSUE THREAD

**Issue by hantt12** [linagora/linshare-mobile-flutter-app#259]
#### Reproduction Steps
1. Go to a workgroup
2. Select multiple files
3. Copy to MySpace

### Expected result
After copying completes, the files in step 2 should be deselected

### Current behavior
The files are still selected

### Context

iphone XR
Linshare app 0.4.0 (37)

https://images.zenhubusercontent.com/309616769/69d95afb-bbeb-4eef-bef3-21f786d3ad9b/img_0112.mp4

**Comment by hoangdat** [comment]
v2.0.0-alpha02
