### ISSUE TITLE
[Story] As an user, i want to add member to my workgroup 

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#274]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC
#160

## Definition

- Given that i am a Linshare user 
- I Logged in the system successfully 
- From menu, go to Shared Space and see the list of my workgroups 
- I touch three dots button of a workgroup. 
-  Choose “Add a member” from Dropdown list. (This option is only enabled for workgroup' admin, and disabled for other roles.) 
-  System will display tab “member”. In this tab, i can see 2 parts:
     * Add a member : This part is only visible for workgroup's admin
     * Existing members: This part is visible for any workgroup's member
   
- On Add a member part, i can see 2 fields:
        1.  Role: I can choose the role for the member I want to add from the dropdown list including options: Admin, Writer, Contributor, Reader. Default value is Reader. 
        2. A search field that when i input text, system will display a suggestion list 

- When i choose a member from the suggestion list: 
     * If the selected user is already in the workgroup, there will be a toast message :" {selected user' name} {selected user's email} is already a member of this workgroup"
     * If there is any error (network, permission change...), there will be an error message 
     
- If is selected user is added successfully to the workgroup, he will be added to the Existing member list. 
- The new member will have respectively rights to the workgroup:
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/64107048-9972-41c1-b83c-1ef82bf700c4)

[Back to Summary](#summary)

### Mockups
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/bae99ab7-e33f-4114-bb1b-53328afcb2cf)None
### Design

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@qpnguyen199 Please add design link for this

**Comment by qpnguyen199** [comment]
Hi, here is the UI design for this story:
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=443%3A3022
