### ISSUE TITLE
[Story] As an user, i want to view file detail in Shared space 

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#283]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

#160

## Definition
**1. View file detail in Shared Space**

-  After logged in to the system successfully, I can go to Shared Space and see the list of workgroups

- I click on a workgroup and see the list of files/folders inside 

-  I click on three-dots button of the file and choose Detail from the Dropdown list

-  I can see detail information of the file as followings :

        *   File name
        *   Size
        *   Creation date
        *   Description (editable)
        *   Modification date and update person

**2. View folder detail**

    • After logged in to the system successfully, I go to Workspace and choose a workgroup and see the list of file/folder
    • I click on three-dots button of a folder and choose Detail from the Dropdown list
    • I can see detail information of the folder as followings :
        *   Folder name
        *   Creation date 
        *   Description 
        *   Modification date and update person

**3. Add/Edit file /folder description in Shared space**

- Given that I am an user on page File/folder detail in Shared space 

-  I can see the field Description. When I click on the button Edit that field, I can add (if there is no description) or edit (if there is already a description). I can only edit this field if i am the contributor/writer/admin of the workgroup 

- I click button cross or enter, the Description is saved. 

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@qpnguyen199 Please add design link

**Comment by qpnguyen199** [comment]
Hi, here is the UI design for this story:
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=3605%3A1
