### ISSUE TITLE
[Story] As an user, i want to rename file in Myspace 

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#284]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

#233

## Definition

- Given that i am a Linshare app's user 

-  I logged in the system successfully

-  From menu, I go to My space

- I click on three-dots button and choose Rename from drop-down list

-  A popup appears allow user to rename the selected file 

-  I input the new name and click button to save. If the new name is valid, system will show successful notification. The old name is replaced. 

- If the new name is invalid, system will display error message 

- The new name is invalid if:

        ◦ It contains a special character : “<”, “>”, “:”, “,”, “/”, “\”, “|”, “?”, “*”, “ “
        ◦ It is blank 
        ◦ It finishes by character "."

[Back to Summary](#summary)

### Mockups 
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/709028a1-f343-461f-9903-b0e54c4e7eb4)
[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@qpnguyen199 Please add design link for this

**Comment by qpnguyen199** [comment]
Hi, here is the UI design for this story:
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=3154%3A1
