### ISSUE TITLE
[Story] As an user, i want to rename file in Shared Space

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#285]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

#160

## Definition

- Given that i am a Linshare app user

- I logged in the system successfully

-  From menu, I go to Shared space, i choose a workgroup and see the list of file/folder in that workgroup

-  I click on three-dots button of a file and choose Rename from drop-down list. I can only see the option Rename if my right to the parent workgroup is Admin/writer/contributor.

- A popup appears allow user to rename the selected file 

- I input the new name and click button to save. If the new name is valid,the old file name is replaced by the new name 

- If the new name is invalid, system will display error message 

- The new name is invalid if:

        ◦ It contains a special character : “<”, “>”, “:”, “,”, “/”, “\”, “|”, “?”, “*”, “" “
        ◦ It is blank 
        ◦ It finishes by character "."

- If the new name is as same as one of existing file name in current Workgroup/folder , system will prompt error message.     

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@qpnguyen199 please add design link for it

**Comment by qpnguyen199** [comment]
Hi, here is the UI design for this user story:
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=3154%3A1741
