### ISSUE TITLE
[Dev] Upload outside app when user not logged in

### ISSUE THREAD

**Issue by manhduc-nguyen** [linagora/linshare-mobile-flutter-app#294]
**DoD**

- When user share files from other apps to LinShare, case of user not log in to LinShare yet. show log in screen.

- After user logged in successfully, upload pending shared files.

**Description**

- Update class `UploadFileManager` to have pending files work with not log in case

**Comment by datnguyenhuy** [comment]
Function works well !
https://images.zenhubusercontent.com/309616769/d53bd7f2-61be-414a-a8f9-45f98a785498/signal_2021_05_20_113705.mp4
