### ISSUE TITLE
Create Workgroup

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#300]
### Story:
#206 - UC1

### Description:
- `SharedSpaceRepository`
- API:
```
@POST("/shared_spaces")
@BODY class CreateWorkGroupRequest(val name: String, val nodeType: LinShareNodeType)
```

### DoD:
- Workgroup is created with name from user
- List workgroup is refresh after created workgroup

**Comment by datnguyenhuy** [comment]
Function works well !
