### ISSUE TITLE
Incorrectly sort by name

### ISSUE THREAD

**Issue by hantt12** [linagora/linshare-mobile-flutter-app#304]
Both MySpace and Shared Space
Iphone XR, ios 14.4
Linshare 0.5.0 (39)
![IMG_0126.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/9f0f08f6-3307-4d5d-8f5c-a8e034433e59)

**Comment by hoangdat** [comment]
what the error? We can not understand what problem with us?

**Comment by hantt12** [comment]
As you can see from the screenshot, ordering by name is not correct: h > g > d > a> [ > P > I

**Comment by dab246** [comment]
Fixed at https://github.com/linagora/linshare-mobile-flutter-app/pull/305

**Comment by hoangdat** [comment]
Resolved in `v0.6.0`
