### ISSUE TITLE
IOS/App crashes when user export png/jpg files from workgroup

### ISSUE THREAD

**Issue by hantt12** [linagora/linshare-mobile-flutter-app#314]
Tested in LInshare 0.5.0 (39)
Iphone 11/iphone XR

https://images.zenhubusercontent.com/309616769/f6a5d4b4-0690-4deb-81a5-cf4f0dc4a8fa/rpreplay_final1617866967.mp4

**Comment by hoangdat** [comment]
Can not reproduce 12Apr21
