### ISSUE TITLE
App keeps loading (need more investigation)

### ISSUE THREAD

**Issue by hantt12** [linagora/linshare-mobile-flutter-app#317]
Sometimes app keeps loading and user needs to kill app and open app again to make it work again
- MySpace loading
- Shared space shows error

Need more investigation to reproduce the issue but it happens quite often

Tested in Iphone11/XR
Linshare 0.5.0

**Comment by hoangdat** [comment]
Tracking:

| Date | Behavior | Note |
| ------ | ------ | ------ |
| 12Apr21 | No abnormal behavior | |
