### ISSUE TITLE
Shared Space/Create Folder/ no message when leaving folder name field blank

### ISSUE THREAD

**Issue by hantt12** [linagora/linshare-mobile-flutter-app#320]
### Description
If user does not input name for the folder, folder name should be auto-populated as "New folder + (x)"

#### Reproduction Steps
1. Go to Shared Space
2. Open a workgroup
3. Click (+) button and select Create Folder
4. DON'T input anything to folder name field
5. Click Create button

### Expected result
Create a new folder named "New Folder +(x)"
For example if there is no folder named "New Folder" => the new folder's name will be "New Folder"
If there is existing folder named "New Folder" then the new folder's name will be "New Folder (1)"

### Current behavior
App closes the dialog, no folder is created. No message is shown

### Context

iphone 11, iphone XR
Linshare 0.5.0 (39)

https://images.zenhubusercontent.com/309616769/66ac69f6-a70a-42f6-8307-eff0c5420881/rpreplay_final1617952663.mp4

**Comment by imGok** [comment]
I've done it before put it has been removed with rebase I guess, I made a PR again
