### ISSUE TITLE
Inappropriate message is shown when user cancels preparing to preview

### ISSUE THREAD

**Issue by hantt12** [linagora/linshare-mobile-flutter-app#321]
#### Reproduction Steps
1. Go to MySpace/Shared Space workgroup
2. Tap a certain file to preview
3. In Preparing to preview dialog, tap Cancel

### Expected result
Preparing to preview dialog closes, no preview is shown

### Current behavior
Dialog closes, no preview but error message "No preview available" is shown

### Context

Iphone 11/XR
Linshare 0.5.0 (39)

https://images.zenhubusercontent.com/309616769/90c3ad55-82c0-4b06-93ad-16deb6730ed4/rpreplay_final1617955871.mp4

**Comment by datnguyenhuy** [comment]
This issue still exists
https://images.zenhubusercontent.com/309616769/e1cc7621-0ba2-408d-880f-6efac136f97e/signal_2021_05_19_162923.mp4

**Comment by hoangdat** [comment]
spend 4h

**Comment by hoangdat** [comment]
spend 4h
