### ISSUE TITLE
[As an user, i want to move file in Shared Space

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#334]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

#160

## Definition

**1.As an user, I want to move a file from a workgroup to a workgroup**
    • Given that i am an Linshare user on page Workspace 
    • I choose a workgroup and see the list of file/folder. 
    • I clicks three-dots button  of a file and choose Move from the drop-down list 
    • A popup will be displayed, allow user to pick the destination. Destination is the list of workgroups in Workspace have roles Admin, Contributor, Writer.
    • After choose a workgroup as the destination and click button to confirm
   • The system will execute moving file to selected workgroup and display successful notification.
    • When I open the original Workgroup, I cannot see the moved file. 

**2. As an user I want to move file from a workgroup to a workgroup's folder**
    • Given that I am an Linshare user on the screen Pick the destination 
    • I choose a workgroup from the list and all the files/folder in that workgroup . 
    • I can continue choosing a child-folder as destination
    • I click button Move here to confirm
    • The system will execute moving file to selected folder and display successful notification.
    • When I open the original workgroup, , I cannot see the moved file. 

**3. As an user , I want to move file/folder to a new created folder.**
    • Given that I am an Linshare user on the screen Pick the destination 
    • I choose a workgroup from the list 
    • I click button “+”, “New folder” popup will be displayed, I can input folder name and click button “Create”, the new folder will be created and displayed 
    • I can choose the new folder as the destination and click button Move here. 
    • The system will execute moving file to new created folder and display successful notification.
    • When I open the original workgroup/folder , I cannot see the moved file.

**4. As an user, I want to move a file/folder to a new created workgroup**
    • Given that i am an Linshare user on page Workspace 
    • I choose a workgroup and see the list of file/folder. 
    • I clicks three-dots button  of a file/folder and choose Move from the drop-down list 
    • A popup will be displayed, allow user to pick the destination.
    • I click button “+” at the bottom bar, “New workgroup” popup will be displayed, I can input workgroup name and click button “Create”, the new workgroup will be created and displayed.
    • I can choose on the new workgroup as the destination and click button Move here.
    • The system will execute moving file to selected folder and display successful notification.
    • When I re-open the destination workgroup, I can see the moved file/folder . 

[Back to Summary](#summary)

## Screenshots
**UC1**
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/9c46d721-bf26-47f3-beca-8d07c3825bd7)
**UC2**
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/43682150-78e3-454c-8f60-72e30c7e1484)
**UC3**
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/11216f68-799d-48cf-960d-1fb3898dd4a2)
**UC4**
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/d5221174-9b70-4d13-bc4e-ebe16d77489f)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@qpnguyen199 Please add design link

**Comment by qpnguyen199** [comment]
HI, here is the UI design for this story:
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=3605%3A1657
