### ISSUE TITLE
[Story] As an user, I want to enable/disable my workgroup versioning

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#335]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

#160

## Definition
  • Given that I am an Linshare app user 
    • Given that i am granted permission to use function “versioning”  and  override the default value of the functionality. 
    • I log in Linshare app successfully and from the menu I go to Shared space screen
    • On the detail screen of a workgroup, I can see the versioning checkbox. I can check/uncheck this box to enable/disable 
versioning function of the selected workgroup. 
    • Note: Only admin of the workgroup can enable/disable versioning function. 
    • Versioning rule: 
        ◦ If I disable the versioning of a workgroup, when I upload a file with the same name as an existing file, the new 
file will be indexed = old file name + n so that the new file name is not duplicated. 
        ◦ If I enable the versioning of a workgroup, when i upload a file that has same name with an existing file, the  
existing file will be versioned as the older one  and system will display a notification “A new version of [File name] has been successfully uploaded”
    • This rule is also applied for other cases : Copy/move a file to a workgroup 

[Back to Summary](#summary)

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/3179a365-b95f-43ed-ad64-8d6ce047cafc)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@qpnguyen199 Please add design link for it

**Comment by qpnguyen199** [comment]
Hi, here is the UI design for this story:
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=3606%3A1
