### ISSUE TITLE
[Story] As an user, i want to manage version of file in Shared Space 

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#337]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

#160

## Definition
-  Given that I am an Linshare app user 
-  Given that versioning is enabled on workgroup  
-  I log in Linshare app successfully and from the menu I go to Shared space screen
-  I choose one of my workgroup and see the list of file/folder 
-  When I click three-dot button of a file, i see a list of actions and  choose option Manage version 
-  All the versions of file are shown with the author name
-  On each version, i can see the options: View detail, download, restore (this option is only enable for old versions,
 disable for current version), Copy , delete.
-  If i am reader, the option Delete and Restore will be disabled 
-  I click button restore an old version, the current version will be replaced by this old version. System will display 
the message: “The version has been restored successfully.” 

[Back to Summary](#summary)

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/4d234b62-9225-47ba-9411-3b9b904bae94)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@qpnguyen199 Please add design link for it

**Comment by qpnguyen199** [comment]
Hi, here is the UI design for this story:
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=3604%3A0
