### ISSUE TITLE
[Dev] Sort SharedSpace in SharedSpace list

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#345]
### Story:
UC1 - #215

### DoD
SharedSpace list will be sorted by Modification Date descending by default.

Show sort status row below action bar

When tap on sort status row, show bottom sheet of other sort options, user can select different options.

### Desciption

See Sort files in MySpace for similar solution

**Comment by datnguyenhuy** [comment]
The sort status row is already displayed below the action bar
User can select different options.
https://images.zenhubusercontent.com/309616769/a0ccdeab-2048-46c7-a5e4-85cd34bb19c7/signal_2021_05_19_170434.mp4
