### ISSUE TITLE
Settings for Biometric Authentication

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#348]
### Story:
#298
#343

### Desc:
- Model: 
```
enum BiometricKind {
    fingerprint,
    faceId,
    none
}
```
```
enum BiometricState {
    enabled,
    disabled
}
```

- Repository:
```dart
abstract class BimoetricRepository {
    Future<boolean> isAvailable();

    Future<List<BiometricKind>> getAvailableBiometrics();

    Future<boolean> authenticate(String localizeReason);

    Future saveBiometricSetting(BiometricState state);

    Future<BiometricState> getBiometricSetting();    // default is `BiometricState.disabled`
    
    Future resetBiometricSetting();    
}
```
`Note:` `stickyAuth` must be set to `True`
- Interactors
`IsAvailableBiometricInteractor`
`GetAvailableBiometricInteractor`
`AuthenticateBiometricInteractor`
`DisableBiometricInteractor`

### DoD:
- Visible or Gone Settings for biometric authentication
- Can enable biometric for app when these are available
- Can disable biometric for app when these are enabled

**Comment by hantt12** [comment]
Please check this bug https://github.com/linagora/linshare-mobile-flutter-app/issues/468
