### ISSUE TITLE
Authenticate with Biometric

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#349]
### Story:
#338

### Desc:
- pseudo code
```
if (getBiometricSetting() == disable) {
    //enter app
} else {  // enabled
    if (authenticate) {
         //enter app
    } else {
         // show screen to retry (max in 3 times) or re-login
    }
}
```
### DoD:
- Only access to application with Biometric whenever it is enabled
- if Biometric enabled and can not authenticate with Biometric => Re-login

**Comment by hantt12** [comment]
Tested in Linshare 0.8.0 with both Fingerprint and Face ID devices
