### ISSUE TITLE
When select `Copy to` in a file in Shared Space Toast with message `No preview available`

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#355]
### Description
When select `Copy to` in a file in Shared Space Toast with message `No preview available`

### Expected result
No unrelated toast is showed

### Current behavior
Toast with message `No preview available`

### Preconditions (optional)
Preview a file with `No preview available` first

#### Reproduction Steps
1. Preview a file with `No preview available` first
2. Context menu button
3. Preview
### Acceptance criteria

The list of acceptance criteria (defined in the corresponding User Story or coming from your functional knowledge of the product)
These acceptance criteria must be met by the corrective implementation done by the developers.

### Context

Android 10, Nokia

### Additional information

frequency, log files,...

**Comment by imGok** [comment]
I followed reproduction steps but remake the bug, can you help me please ? ![whatbug.gif](https://images.zenhubusercontent.com/5ff2d52cfb5a582422c60ab6/34b9133c-00c3-4dc9-bdfc-dd0761f68c36)

**Comment by hoangdat** [comment]
please contact to me to get the hint for that :)

**Comment by huynguyennovem** [comment]
I can not re-procedure this. Pls record a video !
