### ISSUE TITLE
Create CI enviroment for Flutter 2.0 in Bitrise

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#410]
### DoD:
Config to run CI successfully in Bitrise:
- all test run
- build success

**Comment by huynguyennovem** [comment]
- Overview: 
Migrate to null-safety (Flutter 2.0): https://dart.dev/null-safety/migration-guide

- Environment:
   - Flutter 2.0.5 (stable): https://github.com/flutter/flutter/releases/tag/2.0.5
   - Dart 2.12 (stable): https://dart.dev/get-dart
   - Branch: migrate-null-safety

**Comment by hoangdat** [comment]
PR: https://github.com/linagora/linshare-mobile-flutter-app/pull/392

**Comment by tnstung** [comment]
I have just created a PR https://github.com/linagora/linshare-mobile-flutter-app/pull/413

**Comment by tnstung** [comment]
Done
