### ISSUE TITLE
Unable to rename workgroup

### ISSUE THREAD

**Issue by hantt12** [linagora/linshare-mobile-flutter-app#411]
### Description
users try to rename a workgroup but the name remains unchanged

#### Reproduction Steps

1. User1 goes to shared space
2. Rename workgroup that he is one of the admin

### Expected result
Name can be changed

### Current behavior
System does not prompt any error but the name of the workgroup stays unchanged

https://images.zenhubusercontent.com/309616769/8bc607ec-455b-4378-9b52-8db86738f6ee/rpreplay_final1620802279.mp4

### Context

Iphone 11

**Comment by datnguyenhuy** [comment]
Name has been changed successfully 
https://images.zenhubusercontent.com/309616769/089b988f-dc7d-4e36-9607-b18f4e82e57f/signal_2021_05_19_153256.mp4
