### ISSUE TITLE
Redundant message when no result in search

### ISSUE THREAD

**Issue by hantt12** [linagora/linshare-mobile-flutter-app#421]
### Description
In all screens (received share, myspace, shared space), if user searches and there is no result, the message is duplicate
In my opinion, we can remove "0 result" at the top

Tested in ios 0.7.0 (46)

![signal-2021-05-13-142742.jpeg](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/5e62ccda-17a7-4392-a7dc-4d9ac4815ea7)

**Comment by huynguyennovem** [comment]
Confirm this bug is fixed in ver 2.0.0
https://github.com/linagora/linshare-mobile-flutter-app/commit/064ab96301359c34ed1c271e8dcca022041e3f12
![Screenshot_1633086286.png](https://images.zenhubusercontent.com/605175c4593ffb54122f0753/969aa8c3-1305-45b2-af35-f1164301c918)
