### ISSUE TITLE
[Crash] Export files in Shared Space Document 

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#422]
Reproduce:
- Select multiple files in Shared Space -> export -> crash
Or
- Context menu -> export -> crash

**Comment by datnguyenhuy** [comment]
Select multiple files in Shared Space -> Context menu -> Export file successful
https://images.zenhubusercontent.com/309616769/57f4a0bb-727a-4e20-83f7-ba82c7910c8b/signal_2021_05_19_160807.mp4
