### ISSUE TITLE
Activities are not listed

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#423]
### Reproduce:
- admin -> create a workgroup -> add some files, add some members -> check details -> activities
=> nothing showed

**Comment by datnguyenhuy** [comment]
admin -> create a workgroup -> add some files, add some members -> check details -> activities
=> The activities are fully displayed https://images.zenhubusercontent.com/309616769/f3536df8-054f-4ed2-9858-fa595dfc2c5e/signal_2021_05_19_151714.mp4
