### ISSUE TITLE
Inconsistent message when copying file from Workgroup to MySpace

### ISSUE THREAD

**Issue by hantt12** [linagora/linshare-mobile-flutter-app#461]
Scenario 1: 
- Copy a single file from workgroup to Myspace when file size > file size limit of that certain user
=> current message: The file could not be copied

Scenario 2: 
- Copy multiple file from workgroup to myspace  when file size > file size limit of that certain user
=> Current message: Can not copy files to My Space

https://images.zenhubusercontent.com/309616769/f861e716-5eaa-472c-9500-51dac0453e69/rpreplay_final1621907340.mp4

**Comment by imGok** [comment]
@hantt12 you suggest "Can not copy the file" instead of "The file could not be copied" ?

**Comment by hoangdat** [comment]
please select `The file could not be copied` for one and `The files could not be copied` for other

**Comment by imGok** [comment]
ok
