### ISSUE TITLE
App crashes after user fails to enable biometric authentication by fingerprint

### ISSUE THREAD

**Issue by hantt12** [linagora/linshare-mobile-flutter-app#468]
#### Reproduction Steps
1. Use iPhone device with fingerprint authentication
2. Install linshare app and login
3. Go to Account Details
4. Try to enable biometric authentication but use a finger that is not registered in the device
5. Repeat step 4 for a few times

### Expected result
Biometric authentication option remains disabled

### Current behavior
App crashes.
Open app again and go to Account details => Biometric authentication option is no longer shown
Reinstall app and login the same account again => Biometric authentication is still not shown
Login using another account: option is still not shown

Option will be shown after user restarts device

### Context

Iphone 7
Linshare 0.8.0

**Comment by huynguyennovem** [comment]
- Tested on another device (this bug does not occur):
**Iphone 8 (iOS 14.5)**

https://images.zenhubusercontent.com/309616769/98a23e6d-5ea8-491b-8b5e-bcb85e194391/screen_recording_2021_09_21_at_14_02_28.mp4
