### ISSUE TITLE
[Story] As an user, i want to download multiple files in workgroup

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#47]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC
https://github.com/linagora/linshare-mobile-flutter-app/issues/43
## Definition

* Given that i am a Linshare user
* After log-in successfully, i go to Shared space
* On Shares Space, i can see list of workgroups
* I choose one workgroup, then the list of file/folders inside that workgroup is displayed 
* When I long-press on a file from the list, the file is selected and [the multiple files option bar](#multiple-files-option-bar) will be displayed.
* Now in each file, there will be a checkbox. If i tick that box, the file is selected and the selected items counting field at the top bar is added.
* In the multiple files option bar, i can see some icons:
  * Download icon
  * Delete icon
  * Move icon
  * Checkbox: If i tick the box, all the file in the workgroup will be selected. If i un-check the box, all the files will be deselect.
* After selecting multiple files, there are 2 ways to download multiple selected files :
  * I click on icon Download on the top bar
  * Or i can click on three-dot button on top bar, [a list of actions](#list-of-action-popup) will be open. I can see the full options: Download, Delete, Move, Duplicate, Copy to a workgroup, Copy to Myspace. I touch the button Download 
*  The download executed  to save the selected files:
      * If device is Android, the notifcation bar will display all the downloaded file with its's status
      * If the device is IOS, there will be a destination picker screen that allow me to choose the destinationn

*  When the download is completed, I can see the notification on the device. When I touch the noti, I can see local folder containing downloaded files. 
*  If there is an error that make downloading fails (connection, file size, storage space...), i can see a notification on the device. 
*  I can download multiple files from workgroup or from a selected folder in a workgroup 
*  I can download multiple files no matter what is my role in that workgroup: Admin/contributor/writer/reader. 

[Back to Summary](#summary)

### Multiple files option bar

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/72bda6ac-ef19-40c9-8519-ac4f02f20c3b)

### List of action popup

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/db761cff-1fbb-4de9-9c50-b37ce03aaa2e)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@qpnguyen199

**Comment by qpnguyen199** [comment]
Hi, here is the UI Design for this story:
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=2609%3A547
