### ISSUE TITLE
Bad display in biometric authentication screen

### ISSUE THREAD

**Issue by hantt12** [linagora/linshare-mobile-flutter-app#470]
Tested in Linshare app 0.8.0
Both fingerprint and faceid

![IMG_0334.PNG](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/56fb1f15-a20a-4c62-a28e-470dc4dbfc45)

**Comment by huynguyennovem** [comment]
This bug does not occur anymore.
Re-test with Iphone 8 (iOS 14.0) and Iphone 12 Pro (iOS 14.5): 

https://images.zenhubusercontent.com/309616769/0cbd2f82-0f83-4298-8cb0-7442975b156e/demo_ios_authen_biometric_ok.mp4

**Comment by hoangdat** [comment]
need more check to improvement.
