### ISSUE TITLE
Landscape/ "Go to setup" screen is not shown fully

### ISSUE THREAD

**Issue by hantt12** [linagora/linshare-mobile-flutter-app#473]
![IMG_6146.PNG](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/44802d37-268b-4241-a7a9-8ea765562532)

**Comment by huynguyennovem** [comment]
Confirm this is fixed:
https://user-images.githubusercontent.com/29337364/133371437-ade14398-3e24-4b43-9faf-323aa0c84f09.mp4
