### ISSUE TITLE
Android/ sometimes user is unable to login with 2FA enabled 

### ISSUE THREAD

**Issue by hantt12** [linagora/linshare-mobile-flutter-app#481]
### Description
User should always be able to login with correct OTP

#### Reproduction Steps
1. Admin enables 2FA
2. User setup 2FA 
3. User login in Linshare app 
4. Input correct username and password
5. Input correct OTP

### Expected result
Login successfully

### Current behavior
Show Login form again
=> Tap Login button 
=> Show message for incorrect username/password. Account is locked

### Context

Android devices. 
I don't see this error in iOS

Redmi Note9/Android 10
Linshare 4.0

**Comment by huynguyennovem** [comment]
- Update on 16/09/2021:
Can not re-procedure this anytime. It only occurs  5-10% of total test
