### ISSUE TITLE
[Story] As an user, i want to move multiple files  in a workgroup

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#49]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

#43

## Definition

Given that i am a Linshare user

* After log-in successfully, i go to Shared space
* On Shared space, i can see list of workgroups
* I choose one workgroup, then the list of file/folders inside that workgroup is displayed
* When I long-press on a file from the list, the file is selected and [the multiple files option bar](#multiple-files-option-bar) will be displayed.
* Now in each file, there will be a checkbox. If i tick that box, the file is selected and the selected items counting field at the top bar is added.
* In the multiple files option bar, i can see some icons:
  * Download icon
  * Delete icon
  * Move icon
  * Checkbox: If i tick the box, all the file in the workgroup will be selected. If i un-check the box, all the files will be deselect.
* After selecting multiple files, there are 2 ways to move multiple selected files :
  * I click on icon Move on the top bar
  * Or i can click on three-dot button on top bar, a [list of actions ](#list-of-actions)will be open. I can see the full options: Download, Delete, Move, Duplicate, Copy to a workgroup, Copy to Myspace. I touch the button Move
* The Pick destination popup will be displayed. I can continue process as #283
* After moving, i can see those files disappear from original workgroup and displayed in destination directory
* I can move multiple files if i am writer/admin of the selected workgroup. For user whose role are reader/contributor, the option Move will be disabled on Multiple file option bar and List of action popup.

[Back to Summary](#summary)

### Multiple files option bar

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/ef61b7a1-81ff-44d7-8507-c0267d4f64ce)

### List of actions

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/d985bad7-d9ba-467a-8ffe-7b5bb6a6e5d8)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@qpnguyen199 Please add design link

**Comment by qpnguyen199** [comment]
Hi, here is the UI design for this story:
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=3605%3A3263
