### ISSUE TITLE
Android/Unable to preview file in Received shares/MySpace/Shared Space

### ISSUE THREAD

**Issue by hantt12** [linagora/linshare-mobile-flutter-app#491]
user is not able to preview file in all screens
Tested in Android 10/ Redmi Note 9/Linshare 4.0/Linshare app 0.9.0

https://images.zenhubusercontent.com/309616769/a050b723-b80e-4129-8dbb-299e799a2722/video7384f1f1_d05f_447f_b3a1_127a7e471fadvideo.mp4
https://images.zenhubusercontent.com/309616769/c6c9564e-2e61-4d1e-b2e5-2850c8319986/video45441d4b_af6d_472d_9148_c3386bbd4268video.mp4
https://images.zenhubusercontent.com/309616769/7720be2b-4c60-42ba-80fb-99d3e6502efb/videob04db43d_a000_4682_bd00_31d8877cb171video.mp4

**Comment by imGok** [comment]
![previewevew.gif](https://images.zenhubusercontent.com/5ff2d52cfb5a582422c60ab6/12665bd3-299d-4cd2-b8c6-eaec20ad777c) this works for me, can you check again pls

**Comment by hoangdat** [comment]
it works normally
