### ISSUE TITLE
[Dev] Sort in List of Upload requests in a group

### ISSUE THREAD

**Issue by huynguyennovem** [linagora/linshare-mobile-flutter-app#513]
### Story
#449

### DoD:
- User can sort Upload request list order by:
    - label
    - status
    - type
    - activation date
    - expiration date
    - modification date
    - creation date

**Comment by imGok** [comment]
I need more details on Status and Type how should I sort them pls ? 
+ what is the default mode

**Comment by huynguyennovem** [comment]
> I need more details on Status and Type how should I sort them pls ?
> 
> * what is the default mode

You can check it from web version: https://user.linshare-4-1.integration-linshare.org/
As I checked, the default sorter is `Modification date`

**Comment by imGok** [comment]
I checked on the web version but it doesn't really help me, I can see that in Active/Closed tab, Active status is after Closed/Status but that's all

**Comment by huynguyennovem** [comment]
You can filter by status attribute here. 
<img width="1424" alt="Screen Shot 2021-07-29 at 12 50 32" src="https://user-images.githubusercontent.com/29337364/127438668-7a3b31e3-69d9-4c2b-a90c-5a73c1f68d7c.png">
