### ISSUE TITLE
[Dev] OIDC on-premise in deployment

### ISSUE THREAD

**Issue by huynguyennovem** [linagora/linshare-mobile-flutter-app#542]
### Story
#541

### Description
Give a solution for OIDC on-premise

**Comment by hoangdat** [comment]
Can you update sth about the progress?

**Comment by huynguyennovem** [comment]
/spend 8h (14 Jul)
/spend 8h (15 Jul)

- What I did:
    - Study about on-premise offer and security
    - Prepare a slide about OIDC configuration issue and solution
- What next:
    - Works with backend team to have a suitable solution for on-premise offer

**Comment by hoangdat** [comment]
completed but UI is not approved
