### ISSUE TITLE
[Story] As an user, i want to add recipient to an UR 

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#555]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

https://app.zenhub.com/workspaces/linshare-flutter-5fe04e3547c3510015c66915/issues/linagora/linshare-mobile-flutter-app/455

## Definition
-  Given that i am a Linshare user,I log-in the system successfully.
- From the menu, I choose Upload request, I can see 3 tabs: 
        ◦ Pending: Listing URs that have status “Pending”
        ◦ Active+Closed: Listing Urs that have status Active or Closed
        ◦ Archived: Listing Urs that have status Archived
- I can only add recipients to URs that have status “ Pending” or “Active”. There are 2 ways to add recipient to an UR: 
        ◦ 1. In t UR list screen, I click on three-dot button of a Pending or Active UR, the list of actions will be displayed, I
 choose option Add recipients, the screen “Add recipients” appears
        ◦ 2. In UR list screen, I click on an Pending/Active UR, system will open the listing files view if the UR is 
collective and the recipient list if the UR is  individual. I click on “Add people”  button at the bottom of screen, system also open the Add recipient screen.
- In Add recipient screen, I can see a field that allow me to input recipient. The recipient can be an internal email or
 an external email. 
-  When I input characters, the system will show the suggestion email list that matched, and auto-complete the email 
address . 
- If the email format is incorrect, the field Add recipient will be red highlighted with an error message" Invalid email address"
- If the email is already exists in recipients list, when i select that email from the suggestion list, there will be an error message: The email already exists in the recipient list" 
- I select an valid email from suggestion list, it will be added to the list below with an icon to remove it from the list. Then i can continue adding multiple recipients 
- After choosing the recipients, I click button Add, a confirmation popup will be displayed.
-  If I choose Yes, the new recipients will be added to the UR:
        ◦ The new recipient will receive the Upload request in his email as older recipients before and when I open View detail of that UR, I can see the new recipients in the recipient list 

[Back to Summary](#summary)

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/48dad949-595f-421f-b44f-e1aa638e9024)  ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/efbb2388-1c02-475b-8de2-1528f79c3d28)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/25946056-a5cd-4e35-ba42-21399d94d7fb)  ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/6f3aa063-cdd8-4da8-8294-5abd0cf1b342)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/2f88cd38-c221-4671-9ffe-030a1170d36e)  ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/bc20a388-29a5-449a-a08f-1fb9da37c527)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/f0b3423f-8e5a-4943-b99f-8b9e8680cf63)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dab246** [comment]
This ticket has already been completed. Please check again.
