### ISSUE TITLE
Failed to share file from other app to LinShare

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#592]
### Step:

https://images.zenhubusercontent.com/309616769/178611eb-539e-48d6-bbf0-82ed2b298616/can_not_share_from_other_app.mp4

### Evn:
- LinShare 4.1
- Both Android & iOS

### Expect:
- Share widget need to be showed
- File must be shared

**Comment by huynguyennovem** [comment]
Confirm this bug is fixed:

https://images.zenhubusercontent.com/309616769/dc913b7a-06be-4991-b4d7-cb951e1e4a0d/screen_recording_2021_10_01_at_16_51_51.mp4
