### ISSUE TITLE
[Story] As an user, i want to copy multiple files from 1 of my workgroup to Myspace

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#60]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC
https://app.zenhub.com/workspaces/linshare-flutter-5fe04e3547c3510015c66915/issues/linagora/linshare-mobile-flutter-app/43

## Definition

 Given that i am a Linshare user
* After log-in successfully, i go to Shared space
* On Shared Space, i can see list of workgroups
* I choose one workgroup, then the list of file/folders inside that workgroup is displayed 
* When I long-press on a file from the list, the file is selected and [the multiple files option bar](#multiple-files-option-bar) will be displayed.
* Now in each file/folder, there will be a checkbox. If i tick that box, the file/folder is selected and the selected items counting field at the top bar is added. Only when all items i selected are files, the option Copy is enabled on the action list below.
* In the multiple files option bar, i can see some icons:
  * Download icon
  * Delete icon
  * Move icon
  * Checkbox: If i tick the box, all the files/folder in the workgroup will be selected. If i un-check the box, all the files/folders will be deselect.
* After selecting multiple files, i can click on three-dot button on top bar, a [list of actions](#2-list-of-actions) will be open. I choose the option " Copy to My space", all the system will copy selected files to Myspace and display successful toast message.
*  Now when i open Myspace, i can see all the copied files here. 

[Back to Summary](#summary)

#### Multiple files option bar

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/f1a16918-ee32-4268-8510-17a633f67123)

#### List of action popup

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/ffb3c5ed-2bd9-4d3b-b011-27e557cba319)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
@imGok this is story for your task

**Comment by hantt12** [comment]
Please check issue
https://github.com/linagora/linshare-mobile-flutter-app/issues/461
https://github.com/linagora/linshare-mobile-flutter-app/issues/462
https://github.com/linagora/linshare-mobile-flutter-app/issues/463
