### ISSUE TITLE
Upload to Workgroup from outside application

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#63]
### DoD:
- Can choose the destination in Workgroup (root or sub folder also)
- Only upload to workgroup with have the right permission
- Can upload successfully to chosen destination

**Comment by hoangdat** [comment]
@imGok I created configs to enable share multiple files with LinShare. Please continue work on that.

**Comment by hantt12** [comment]
Unable to upload from outside because the Upload Confirmation screen is not shown
