### ISSUE TITLE
Text is overflowed on MySpace screen

### ISSUE THREAD

**Issue by huynguyennovem** [linagora/linshare-mobile-flutter-app#630]
### Description
Text is overflowed on MySpace screen

### Expected result
Text is not overflowed and displays normally

### Current behavior
![Simulator Screen Shot - iPad Pro (9.7-inch) - 2021-09-20 at 11.07.16.png](https://images.zenhubusercontent.com/605175c4593ffb54122f0753/e7151206-276c-43da-8f61-6b549302f49a)

### Context
Ipad 9.7 inch (iOS 14.5)

**Comment by hoangdat** [comment]
@huynguyennovem please update the status of this ticket, if you fixed it, please reference PR (using github link by #XXX)
