### ISSUE TITLE
[Bug] File did not make offline is showing offline icon

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#649]
### Current behavior

1. Logged in with user 1
2. Select a workgroup `X`, which have member: (user1, user2, ...)
3. Select a file `F` on `X` then make available offline
4. Logout
5. Logged in with user2
6. Open the workgroup `X`
7. Check the file `F` 

### Acceptance criteria

The list of acceptance criteria (defined in the corresponding User Story or coming from your functional knowledge of the product)
These acceptance criteria must be met by the corrective implementation done by the developers.

### Context

Devices, OS

### Additional information

frequency, log files,...

**Comment by huynguyennovem** [comment]
Can't re-procedure. Can you record a video?
