### ISSUE TITLE
Upload multiples files to MySpace

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#65]
### Story:
#45

### Description:
- `taskId` <-> file
- upload execute will response `taskId`
- stream for progress in data source
- Kill all uncompleted upload tasks when re-start app (in main())

### DoD:
- multiple files can be uploaded to MySpace
- uploading task in previous uploading turn is not discard by the next uploading 
- uploading files is show in upload screen
- multiple upload can be executed in both case: outside & inside

**Comment by hoangdat** [comment]
one question: how about when we need to `upload and share`? @manhduc-nguyen @ngohado

**Comment by hantt12** [comment]
As discussed with @hoangdat uploading from outside will be handled in another backlog
