### ISSUE TITLE
[Story] As an user, I want to log-in LinShare app with my SSO account

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#662]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a LinShare app user 
- Given that my LinShare is integrated with OIDC provider. 
- When I open the app, the Log-in screen will be opened 

### 1. In the Log-in screen:
      - If I click on button Sign in to Saas, the browser will be opened with OIDC log-in screen
      - I input my SSO account credentials, then the OIDC provider will validate.
      - If the information is valid, I will log-in successfully to the LinShare app 

### 2. In the Log-in screen, I click button "Sign in to self-hosted instance"
- I can see 2 options: Sign-in with user's credentials and Sign in with SSO
#### 2.1 Sign in with user's credentials: I need to input URL, user name, password: The app will validate as currently

```
As an user, when I input wrong url, I want to change the url to re-login again
```
```
As an user, when I input wrong email or password, I want to change the email/password to re-login
```
```
As an user, when I input url, email, password correctly I can access to LinShare
```
#### 2.2 Sign in with SSO: I need to input URL
   - If the URL is valid, the browser will be opened with OIDC log-in screen 
      - I input my SSO account credentials, then the OIDC provider will validate.
      - If the information is valid, I will log-in successfully to the LinShare app.
   - If the URL is invalid, system will display error message and the field URL is highlighted in red border 

### 3.  I can click on the "Sign up" to navigate to the sign-up page of Saas
     
[Back to Summary](#summary)

## Screenshots

![image](https://user-images.githubusercontent.com/68209176/137254589-f67e081b-ae4b-458f-a3ed-2e05613f4a83.png) ![image](https://user-images.githubusercontent.com/68209176/137254598-ab9f9b48-6b69-4a61-b952-cccd5acd651e.png)

![image](https://user-images.githubusercontent.com/68209176/137275020-e6881da2-e4eb-4357-ab3f-e1cb3d5acf18.png) ![image](https://user-images.githubusercontent.com/68209176/137275033-08750734-0847-4ded-a384-84df94ccd546.png)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@hoangdat

**Comment by dieptran88** [comment]
Story is updated, please check

**Comment by dieptran88** [comment]
> > Story is updated, please check
> 
> As the last meeting (13 Oct), we need the `Sign up` button also. Please add it on the mock-up. Thanks, @dieptran88

done

**Comment by fmartin-linagora** [comment]
what does represent the 4th screenshot ?

Can we have the "or" in a bubble like the "Sign in" button ? Maybe a white bubble with a blue font. WDYT ?

**Comment by dieptran88** [comment]
> what does represent the 4th screenshot ?
> 
> Can we have the "or" in a bubble like the "Sign in" button ? Maybe a white bubble with a blue font. WDYT ?

the 4th screen is for log-in with SSO but with self-hosted instance, no?
and white bubble  like this ?
![image](https://user-images.githubusercontent.com/68209176/137273877-1152036e-f8b0-49f9-a183-206939eaa44a.png)

**Comment by fmartin-linagora** [comment]
Oh yes, you're right for the 4th screen ! :+1:

**Comment by hoangdat** [comment]
- [ ] update new version for `flutter_appauth`
- [ ] get config from: `baseUrl/config/config.js`
- [ ] get `client-id` and `authority` then execute PKCE

![image](https://user-images.githubusercontent.com/6462404/140004951-d0533065-b3c1-4456-a90f-ecd47b4810d9.png)

**Comment by hoangdat** [comment]
![image](https://user-images.githubusercontent.com/6462404/140493937-4675299a-e55d-44a9-b402-c67676cec5b5.png)

**Comment by fmartin-linagora** [comment]
Linagora => LINAGORA.

**Comment by fmartin-linagora** [comment]
is it really LINAGORA'server which is used as  default value ? is it rather LINAGORA Saas patform ?

**Comment by fmartin-linagora** [comment]
by the it is a screenshot of twake on a LinShare story ;)

**Comment by hoangdat** [comment]
https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App
