### ISSUE TITLE
[Story] As an user, I want to to advanced search  in a workgoup/folder.

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#668]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

#### Preconditions
- Given that i am a LinShare user.
- Given that "Workgroup" functionality is enabled in Admin.

**UC1. Search files or folders inside a workgroup/folder**

- After logged-in successfully to LinShare, i go to Shared Space and see the list of workgroups.
- I click on a workgroup and see the list of files/folders inside.
- I can see the search bar on top of the screen and click on icon setting on the right
- A new screen Advanced Search settings will be displayed and i can see the list of search criteria including:
   - Type: I can see checkboxes: Images/Documents/PDFs/Spreadsheets/Presentations/Audio/Archive /Folder/Other
   - The default option is all: I can choose "Select all" to tick all the checkboxes or "Clear all" to remove all the ticks
   - Modification date: A drop-down list with the default option is "Any time". When I click on this field, a list of options will be shown and I can select only one option: past day, past week, past month, past year. After I select 1 option, the list of options will be collapsed .
- After choosing search critetia, I click button Apply , the Advanced search settings screen is closed and back to the search box . If I click Reset, all criteria will be cleared.
- Now the icon setting on the right of search box is bold. If advanced search setting is not applied, this icon will be grey 
- I input characters on the field " Search by name"
- The system will search files and folders name  inside that workgroup and display search result instantly in the list below 
- The result will include not only files/folders at first level of the workgroup but also files/folder at child levels of folders inside the workgroup

#### Postconditions

- The result will include not only files/folders at first level of the workgroup but also files/folder at child levels of folders inside the workgroup.
- In result list, with each item, i can see a full path below each item if the result is not in current workgroup
- When i click on three-dots button of a file in the list, i can see the options: Details, Go to destination, Preview, Download.
- When i click on a file, it will open file preview
- When I click on a folder, it will direct to folder location
- The advanced Search criteria will be removed after I close Search result screen.

Back to Summary

[Back to Summary](#summary)

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/e5106b2a-5d44-45c1-a40e-c32411250fff) ![image](https://user-images.githubusercontent.com/68209176/138018405-b64844ba-142f-4bda-9ca5-36168a7fcccc.png)

![image](https://user-images.githubusercontent.com/68209176/138018435-2876cc58-397d-418e-9cc9-fadb817a1b19.png)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/303c84f1-7f38-4b3e-919a-3ab9695e27cc) ![image](https://user-images.githubusercontent.com/68209176/138018493-5b67fe40-eed6-4a13-879a-cb5d6d6f36b6.png)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
I prefer the simpler screen for user in mobile. How about the criteria will be showed as list of tags, user can only select or unselect to filter? 

@huynguyennovem please discuss about it

**Comment by huynguyennovem** [comment]
2. `If Type Files or Versions is not selected, then the field File type is disabled/hidden.`
I think if the Versions is not selected, the field File type is still shown/enable

**Comment by huynguyennovem** [comment]
3. About `Creation date` and `Modification date`:
The selection should be radio button instead of check box. The reason is that if user selects both `Past day` and `Past week`, the `Past day` is no meaning because the `Past week` already contains `Past day`.

**Comment by huynguyennovem** [comment]
4. `When i click on one item, it will go directly to the location of that item.`
Hmm, I'm not clear about this. Currently, if the item is a file, it should be preview and if the item is folder, it will go to inside of the folder. It should keep this logic, IMO

**Comment by hoangdat** [comment]
>  If we don't search the child level, this action is not necessary too.

We're trying to search more powerful than only in one level of folder.

**Comment by hknguyen91** [comment]
Hello guy @hoangdat  @huynguyennovem  @dieptran88 I'm working on Advanced Search now, I have some changes:
- New color
- Check Advanced search setting will show up from the bottom, It will satisfy the user's fingers, it's easier to tab:
![image](https://user-images.githubusercontent.com/95336527/148736529-abb2c97a-c235-40d9-a213-322f1bc76d7b.png)
![image](https://user-images.githubusercontent.com/95336527/148736559-0f27168f-95a3-4c09-9147-6b519f1f4224.png)
- update icon drive 
- Filter out of the search box
- Path only in details

UI:https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=5214%3A39792

**Comment by hoangdat** [comment]
Seems good in design. Thank Khanh.

But I am not clear about. Can you explain more about it?

> Path only in details

**Comment by hknguyen91** [comment]
@hoangdat  I think seeing a path in the search result  is a bit difficult  to remember, and what if the path is too long? And 1 more thing if the user wants to use the path for some actions, for example, go to a destination,  we should have a copy path button next to the path? so it's better in another place that has space, like details 
![image](https://user-images.githubusercontent.com/95336527/148743815-e0eaf325-6d04-40b0-a10e-2a5b13d102d4.png)

**Comment by hknguyen91** [comment]
if I want to use the path, it's better to have a copy button like this: 
![image](https://user-images.githubusercontent.com/95336527/148744064-8d05cc1a-146e-4f3e-b4ac-3000d12e91cf.png)
