### ISSUE TITLE
[Story] As an user, I want to View list of drive/workgroup in Shared space

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#710]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

#### Preconditions

*  Given that i am a Linshare app user 
*  Given that the functionality of Drives is enabled in Admin setting

#### Description

**UC1. View list of workgroups/drives in Share Space**

*  After logged-in successfully, I go to Shared Space 
*  I can see the list of my drives and workgroups that are not inside any drives 
*  When i  click button "+" at bottom of screen, there will be 2 options: Create a drive / Create a workgroup
*  If the functionality of Drives is disabled in Admin setting, when i click button +, the option Create a drive is not shown

**UC2. Sorting list in Shared Space**

*  On top right of screen, I can see a sorting icon
*  when i click on this icon, i can see dropdown-list of sorting criteria:
   - Modification date
   - Creation date 
   - Name
*  I can choose one of these sorting criteria and double click to change the sorting order 
*  The workgroup/drive  list will change accordingly

**UC3. Search workgoups/drive  by name**
 
 * On top right of screen, i can see  a search bar "Search by name"
 * I can type in this field and the system will display matching result instantly 

#### Postconditions

*  I can see the list of drives that i am a member. 

[Back to Summary](#summary)

#### Mockups

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/7de034c8-3b4b-4b77-9600-6ff59614e1b0)  ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/b5262e40-5e37-4276-8e1f-f544bbf45acd)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/30ecd0d6-98ff-48f5-84ed-aa11b88d9dee)  ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/5d95f304-8b65-40e3-95ac-99d064cf11ac)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/d51f48b3-8e05-4240-906c-93801f4a0434) ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/644990ec-0313-4cfd-9746-87f4fdbad12d)

#### Final design

Design Tikcet
https://ci.linagora.com/linagora/lgs/design/-/issues/54

[Back to Summary](#summary)
## Misc

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
Completed v2.2.0
