### ISSUE TITLE
[Story] As an user, I want to View workgroup list inside a drive

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#713]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

#### Preconditions

*  Given that i am a LinShare app user 
*  Given that the functionality of Drives is enabled in Admin setting

#### Description

**UC1.View list of workgroups**

*  After logged-in successfully, I go to Shared Space 
*  I can see the list of my drives and workgroups that are not inside any drive
*  I click on a drive.
*  I see the list of all workgroups inside my drive. (drives that I am a member of)
- Then I click on a workgroup, I can see the list of folders/Files inside that workgroup 

**UC2. Sorting list of workgroups**

*  On top right of screen, I can see a sorting icon
*  when i click on this icon, i can see  list of sorting criteria:
   - Modification date
   - Creation date 
   - Name
*  I can choose one of these sorting criteria and double click to change the sorting order 
*  The workgroup list will change accordingly

**UC3. Search workgoups by name**
 
 * On top right of screen, i can see  a search bar "Search by name"
 * I can type in this field and the system will display matching result instantly 

[Back to Summary](#summary)

#### Mockups

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/1ea1dca6-bbfa-4678-b062-2fb73aa2cf5e) ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/adac7fb9-8d47-4180-83e0-b238ff2676de)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/2b8bc7ed-fec6-463e-be06-bfc1621ccc32) ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/edeede1e-46aa-41e1-a1ce-1158566384f7)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/44e48e36-2811-486a-8de9-d27dbbc280c1) ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/5ea1331f-9ca4-448a-a451-4489a4694727)

#### Final design
Ticker: 
https://ci.linagora.com/linagora/lgs/design/-/issues/55

[Back to Summary](#summary)
## Misc

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
completed v2.2.0
