### ISSUE TITLE
 As an user, I want to Create workgroup inside a drive

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#715]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* [Drive](./README.md)

#### Preconditions

*  Given that I am a LinShare user 
*  Given that the functionality of Drives is enabled in Admin 

#### Description

*  After logged-in successfully, I go to Shared Space 
*  I can see the list of my drives and workgroups that are not inside any drive.
*  I click on a Drive  and the the list of workgroups inside
*  If I have role Admin/writer to the Drive, I can see the icon "+" is enabled at the bottom of screen. If I am Drive reader, the icon is disabled 
*  I click on this icon, the popup Create a workgroup is opened with a default name
*  I can edit workgroup name or not then click button Save

#### Postconditions

*  The new workgroup is created , there will be a successful notification message and I can see the new created workgroup in the first of the list. The default sort criteria is modification date.
*  If there is any error, there will be an error message:
   - Workgroup' name is blaonk
   - Workgroup name contains special characters 
   - Network error...
*  All the Drive'members are added automatically to the new created workgroup with his default role to Workgroup
*  The creator of the workgroup is workgroup's admin by default.
*  I can see this action on the Drive audit and Workgroup audit. 

[Back to Summary](#summary)

#### Mockups
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/be136356-4e6d-4ad5-84c0-fe3fc1880023)  ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/aebfdbce-43d8-4a03-a242-0b922072c908)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/c25f35fd-4525-4729-a743-dbb1a6609b73) ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/c3fc20e7-c662-46a5-9cd2-997a439276a7)

#### Final design

[Back to Summary](#summary)

## Misc

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@hoangdat  Please review

**Comment by hoangdat** [comment]
completed
