### ISSUE TITLE
Sign-up for SaaS

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#737]
### Design: 

https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-iOS-App?node-id=4884%3A15041

### API:

Verify email: 
https://account-twakeconsole.dev-linshare.lin-saas.dev/api/users/email-availability/laisam114%40gmail.com

1. To signup with SaaS, we need to create a `secretToken`
```
@POST /api/subscriptions/reservation
{...}
```

2. Then use that `secretToken` to call to signUp endpoint when submit signUp form (`email, name, surname` is inputed by user, `passsword` is generated by app) 
```
@POST /api/signup
{
    ...
}
```

**Comment by hoangdat** [comment]
Hi @tuanlc, as you see, we will hard-code the information of Twake console in LinShare app, so please provide us:
- Subscription link 
- Signup url

Please make sure the template of subscription link, signup link is not changed in `dev`, `production`, `qa` env. Fx: `https://supscription.****.console-url.com`. It will easy to us in hard-code (workaround solution)

**Comment by tuanlc** [comment]
Signup flow:

**Step1**: get secretToken by using reservation API
- https://subscription-twakeconsole.dev-linshare.lin-saas.dev/apidoc/static/index.html#/subscription/post_api_subscriptions_reservation
**Step 2**: use secreateToken above to call signup endpoint
- https://account-twakeconsole.dev-linshare.lin-saas.dev/apidoc/static/index.html#/user/post_api_signup
