### ISSUE TITLE
action rights inside drive

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#755]
Action rights inside drive:

- what right to create workgroup?
- what right to delete/edit name workgroup?
- what right to add/delete/edit member and role?
- ...

**Comment by hoangdat** [comment]
@dieptran88 please help me on it

**Comment by dieptran88** [comment]
https://docs.google.com/spreadsheets/d/1YuwWMEftZR5GTWjDU9GA1pVTFY6eUpwi28Xng7-YUqg/edit#gid=1620856673
Please check Permission sheet

**Comment by dieptran88** [comment]
The permission for actions of workgroup inside a drive is as same as standalone workgroup.
