### ISSUE TITLE
Can not create upload request

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#778]
### Desc:

- iOs 14

https://user-images.githubusercontent.com/6462404/144806322-c966de50-ef8e-4152-80ef-e2e21bbc46e5.MOV

**Comment by dab246** [comment]
Tested on ios 14.3 virtual machine. It works well.

https://user-images.githubusercontent.com/80730648/144810143-cf013094-4518-4d83-837f-531c12b78db6.mov

**Comment by hoangdat** [comment]
@dab246 you test on which server?

**Comment by hoangdat** [comment]
please check with: https://user.linshare-5-0-on-commit.integration-linshare.org/.
Maybe the problem come when some configuration is not enable 
![image](https://user-images.githubusercontent.com/6462404/144812753-4c6813c7-36ae-4510-8cfe-403fc8df6b90.png)
