### ISSUE TITLE
[ Story] Merge 2 current functionalities Drives and Workgroups into 1 functionality Shared Space 

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#783]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Definition

* Given that I am LinShare app user
* Depending on the setting of functionality "Shared Space" in admin portal, my LinShare mobile app will be changed accordingly:
* In admin portal, the functionality "Shared Space" is the original function and " Creation right-Drive" and " Creation right-standalone workgroup" are sub-functions, 
* When the original functionality is not activated, the sub-functions will not work
**1. Original function: Shared Space**
- When the activation policy of this functionality is enabled,  when I access my LinShare account, I can see the menu Shared Space
- When the activation policy of this functionality is disabled,  when I access my LinShare account,  the menu Shared Space will be hidden
**2. Sub-function: Creation right-Drive**
- When the activation policy of this functionality is enabled, When I access Shared Space and click Create button, I can see option: "Create drive"
-  When the activation policy of this functionality is disabled, When I access Shared Space and click Create button, I can not see option: "Create drive"
**3. Sub-function: Creation right-standalone workgroup**
- When the activation policy of this functionality is enabled, When I access Shared Space and click Create button,  I can see option: "Create standalone workgroup"
- When the activation policy of this functionality is enabled, When I access Shared Space and click Create button,  I can not see option: "Create standalone workgroup"

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
done for Back-end v5
