### ISSUE TITLE
iOS upload image inside app is not correct format

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#799]
### Expected result

Upload image inside app successfully

### Current behavior

go to MySpace -> Photos and Videos -> select a picture -> upload file screen is display that picture with `.pvt` extension.

![image.png](https://images.zenhubusercontent.com/5f7d8ef759d36aecc684e2a4/c1081cfb-a119-47a6-8505-bbe63027ca98)

iOS 15

**Comment by dab246** [comment]
I've checked for this error. Please check again or provide me with more detailed error pictures and videos.
