### ISSUE TITLE
File size is not correct when upload from outside to Linshare

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#80]
### Description
When uploading from outside to Linshare, the file size should be shown correctly  in Upload confirmation screen

#### Reproduction Steps
1. Open Photos app in Iphone and select a file to upload
2. Select Linshare app to upload to
3. Check file name and file size in Upload confirmation screen

### Expected result
File size should be correct

### Current behaviour
File size is not correct (x1000 times the correct file size)

### Context

IOS, Iphone 7/11 promax
Flutter Linshare app v1.0.0

**Comment by manhduc-nguyen** [comment]
checked, bug no longer exists. Please retest
