### ISSUE TITLE
[Dev] Improve Advanced Search as new design

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#808]
### Story:

#668 

### Desc:

New design was released. Please apply it

### Design:

https://www.figma.com/file/sEBIXTIsTfTb1TKZvMnuGx/LinShare-App-(cross-platform-iO-Android-Tablet)?node-id=5267%3A41943

**Comment by hoangdat** [comment]
@hknguyen91  I see we have 2 options for advanced search.

**Comment by hknguyen91** [comment]
@hoangdat   Yes, pls I  need validation from Dmitry first,  I'll push him more today
