### ISSUE TITLE
Network connection should be available after device connects to network

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#84]
#### Reproduction Steps
1. Kill Linshare app
2. Disconnect device from network
3. Open Linshare app
4. Connect device to network
5. Check Linshare MySpace again

### Expected result
MySpace should be loaded successfully with the list of file

### Current behaviour
Loading takes forever

### Context

Iphone 7, iPhone 11 Promax

Redmi Note 9

**Comment by hantt12** [comment]
In Step 3, app shows Login screen. If user login from this screen, loading icon is shown like forever
