### ISSUE TITLE
Too much data in Document and Data

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#86]
### Description
After using the Linshare for one day, too much data is stored Document and Data. We need to find a way to clear the data

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/afb2953e-d4d1-4124-9a82-3486f05e3fe9)

### Context

Iphone 7, iphone 11 Promax

**Comment by hoangdat** [comment]
> Data is added up after user uploads file to Linshare app
