### ISSUE TITLE
[ Story][SAAS Limitation]  As a user, I want to see the error message when my number of uploaded files per day exceeded the limit 

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#869]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a LinShare user  
- Given that the funnctionality Limit number of uploaded files per day per user is enabled with the limit number is defined.

**UC1. Upload a single file to Myspace**

- When I upload a file to Myspace in LinShare, the system will validate:
   - If my total uploaded files in Myspace today are smaller than value of "Max uploaded file count" (set by domain admin), the uploading is processed as normally
   - If my total uploaded files in Myspace today has reached the value of "Max uploaded file count" (set by domain admin), and I am using LinShare with self-hosted server, there will be an error message: "You have reached maximum number of uploaded files per day."   
   - If my total uploaded files in Myspace today has reached the value of "Max uploaded file count" (set by domain admin), and I am using LinShare SAAS , there will be an error message: "You have reached maximum number of uploaded files per day. Please contact your company owner to upgrade the company plan at [Console link]."

**UC2. As a user, I want to upload multiple files to Myspace with the limitation of number of files**

- If I upload multiple files in once, and the number of uploading files makes my total uploaded files a day greater than the limitation, for example:

   - My limitation is 20 files per day and I have not uploaded any file today
   - On Myspace , I click button Upload and select 25 files from my mobile (inside or outside app) to upload

-  The system will validate:
   - If any file in the list is greater than file size limitation, there will be an error message as currently
   - If there is no available space, there will be an error message for remaining files as currently
   - After the twentieth file is uploaded successfully, there will be an error message: "You have reached maximum number of uploaded file per day".  If I am using LinShare SAAS , the error message will be: "You have reached maximum number of uploaded files per day. Please contact your company owner to upgrade the company plan at [Console link]."

- When I click on the link Console, user is redirected to Console page.

    
[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
@dieptran88 IMO, we need the design for the popup to user in each case
