### ISSUE TITLE
[Story][SAAS Limitation] As a user, I want to see error message when my number of upload requests exceeded the limit 

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#870]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a LinShare user  
- Given that the funnctionality Limit number of upload request per user is enabled with the limit number is defined.
- When I click button create a new Upload request in LinShare, the system will validate:
   - If my total uploaded requests with status: Pending/Active/Close is smaller than value of "Max uploaded request count" (set by domain admin), I can continue creating upload request as normally.
   - If my total uploaded requests with status: Pending/Active/Close has reached the value of "Max uploaded request count" (set by domain admin), the system will check:
      - If I am using LinShare with self-hosted server, there will be an error message: "You have reached maximum number of upload requests."
      - If I am using LinShare SAAS , there will be an error message: "You have reached maximum number of upload requests. Please contact your company owner to upgrade the company plan at [Console link].

- When I click on the link Console, user is redirected to Console page.

    
[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
@dieptran88 IMO, we need the design for the popup to user in each case
