### ISSUE TITLE
[Story][SAAS Limitations] As a user, I want to see error message when I create a new workspace (drive) and the number of workspaces in my domain exceeded the limit 

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#871]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a LinShare user  
- Given that the funnctionality Limit number of  workdpaces in domain is enabled with the limit number is defined.
- When I click button create a new workspace in LinShare, the system will validate:
   - If the current  number of workspaces in my domain is smaller than value of "Max workspace count" (set by domain admin), I can continue creating workspace as normally.
   - If  total workspaces in my domain has reached the value of "Max workspace count" (set by domain admin), the system will check:
      - If I am using LinShare with self-hosted server, there will be an error message: "You have reached maximum number of workspaces ."
      - If I am using LinShare SAAS , there will be an error message: "You have reached maximum number of workspaces. Please contact your company owner to upgrade the company plan at [Console link].

- When I click on the link Console, user is redirected to Console page.

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
@dieptran88 IMO, we need the design for the popup to user in each case
