### ISSUE TITLE
[Story][SAAS Limitations] As a user, I want to see error message when I create a new workgroup and the number of workgroups a workspace (drive) exceeded the limit 

### ISSUE THREAD

**Issue by dieptran88** [linagora/linshare-mobile-flutter-app#872]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a LinShare user  
- Given that the functionality Limit number of nested workgroups in a workspace is enabled with the limit number is defined.
- When I click button create a new workgroup inside a workspace in LinShare, the system will validate:
   - If the current  number of workgroup in workspace is smaller than value of "Max workgroup count" (set by domain admin), I can continue creating workgroup as normally.
   - If  total workgroups in Workspace has reached the value of "Max workgroup count" (set by domain admin), the system will check:
      - If I am using LinShare with self-hosted server, there will be an error message: "You have reached maximum number of workgroups inside this workspace. ."
      - If I am using LinShare SAAS , there will be an error message: "You have reached maximum number of  workgroups inside this workspace. Please contact your company owner to upgrade the company plan  at [Console link].

- When I click on the link Console, user is redirected to Console page.

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
@dieptran88 IMO, we need the design for the popup to user in each case

**Comment by dieptran88** [comment]
Ok if you have request I will transfer to Anh
