### ISSUE TITLE
Add APK file on GitHub release

### ISSUE THREAD

**Issue by alagane** [linagora/linshare-mobile-flutter-app#923]
### Description

The APK file generated by the "Release" GitHub action should also be uploaded to GitHub.

### Expected result

When I am looking at **https://github.com/linagora/linshare-mobile-flutter-app/releases/tag/v3.7.5** for example, I should see something like "LinShare-v3.7.5.apk" on the Assets

### Current behavior

Only the sources are available. The APK file is built but it is only deployed to Google Play.

(https://github.com/linagora/linshare-mobile-flutter-app/actions/runs/4202893330/jobs/7291705555#step:9:1864)

### Context

Android

**Comment by hoangdat** [comment]
@tk-nguyen do you have any idea for our CD?

**Comment by alagane** [comment]
> @tk-nguyen do you have any idea for our CD?

First, add a step after "Build and deploy" to upload artifact (with version in name).

https://github.com/actions/upload-artifact

Next, I guess upload the artifact to release. I don't know if the previous step is needed to do this though.
