### ISSUE TITLE
Unable to upload file from outside

### ISSUE THREAD

**Issue by hantt12** [linagora/linshare-mobile-flutter-app#97]
Steps to reproduce:

1. Login Linshare app
2. Go to Files app, select one file to share
3. Select Linshare app to share to

Expected result:
System shows Upload confirmation screen

Actual result:
System shows MySpace

Tested in iPhone 11 Promax. iOS 13.6
Linshare version 0.1.0 (32)

[video](https://images.zenhubusercontent.com/309616769/11a2741d-7fe2-4fe0-a28d-7780535de086/img_0558.mp4)

**Comment by hantt12** [comment]
Please check this issue again. I can still reproduce it
Tested in LInshare app 0.3.0 (34) using Iphone 11. Ios 14.4

**Comment by hoangdat** [comment]
Can you test this issue @manhduc-nguyen ?

**Comment by hoangdat** [comment]
I have the same issue in iOS14.4 IphoneX

**Comment by manhduc-nguyen** [comment]
I'll check it now. Having the same issue with some files
