### ISSUE TITLE
File is not automatically shown on Shared Space after being uploaded

### ISSUE THREAD

**Issue by hantt12** [linagora/linshare-mobile-flutter-app#99]
Steps to reproduce:
1. Go to Shared Space
2. Go to a workgroup that you are admin/contributor/writer
3. Upload a file
4. Check the list of files in current workgroup/folder after uploading completes

Expected result:
The file is shown

Actual result:
The file is not automatically shown. It's only shown after user refreshes the list

**Comment by hoangdat** [comment]
fix on v2.0.0-alpha02
